### ISSUE TITLE
Remove scale_vectors keyword

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#111]
This is not needed. We do not want to scale something inside gimic. If needed be for visualization scaling can be done eg. in Paraview. If scaling has been done it should be reported.

**Comment by heikef** [comment]
I checked this. This keyword has already been removed. However, it appears in old input files and therefore we thought it is still functioning. This issue can be closed.

**Comment by bast** [comment]
Did it appear in old input files as out-commented keyword? :-) If yes, then you now understand why I always delete such code when I see it.

**Comment by heikef** [comment]
Yes, it was commented out. Therefore we thought it still works. Nobody apparently checked. It was good to put in on the to do list as an issue. Otherwise we would have all forgotten about this. 

Of course it makes sense to delete such stuff. However, from a user point of view it is more convenient to comment things in and out. If I would always proceed like you suggest it (which is of course the cleaner way) we would not have had an example on how to read in the grid files, since that was not in the documentation. Same holds by the way for the divergence and edense modules. Here we have something that does not work and is also not documented. An old input with commented out stuff would be helpful. I found an old input by the way but the code changed too much so we can not use this any more. 

Yes, this shows of course how important testing and documentation is. ;)
