### ISSUE TITLE
Add Valgrind test

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#113]
@mariavd volunteered to take care of this - an important issue to monitor performance

**Comment by mariavd** [comment]
Ages ago I promised to take care of checking the code with Valgrind. No issues appeared, so the next question is, do we want it to run as a separate test like testing a certain keyword, or should we assume that those who add code will also make sure they wrote it properly? The test could look for each value of the lost bytes. 

```
==48556== LEAK SUMMARY:
==48556==    definitely lost: 0 bytes in 0 blocks
==48556==    indirectly lost: 0 bytes in 0 blocks
==48556==      possibly lost: 0 bytes in 0 blocks
==48556==    still reachable: 109 bytes in 3 blocks
==48556==         suppressed: 0 bytes in 0 blocks
```

Just for the sake of reference, I used 
```
export GIMIC_LAUNCHER='valgrind --tool=memcheck --log-file=valgrid-summary.dat --leak-check=full --track-origins=yes --show-reachable=yes'
```
And then just called ``gimic gimic.inp``. It is handy that when it is called, gimic checks for the existence of that environment variable, so no need to recompile or edit anything. Of course, the test analyses only those functions requested for the particular input file. One cannot analyse 3D current density and a bond integral calculation at the same time. 

What do you think, @heikef  and @bast ?

**Comment by bast** [comment]
I think we should add it to the automated testing.

**Comment by mariavd** [comment]
OK, I'm starting to prepare the automated test.

**Comment by bast** [comment]
And forgot to add: thanks for pointing this out, this is a really important aspect to test.

**Comment by mariavd** [comment]
I'm glad to be useful :)

**Comment by mariavd** [comment]
How to handle the case when valgrind is not present on the system. Should it be compiled within Travis?

**Comment by bast** [comment]
It should be installed with Travis, it's an apt package.

**Comment by mariavd** [comment]
In regard to that, in case some part of the automated test does not work locally, say, valgrind is missing locally, how unreasonable is it to commit just so that Travis will run? It is a hypothetical situation but it could potentially happen.

**Comment by bast** [comment]
I think that's fine.

**Comment by mariavd** [comment]
Should we test the release version where the output from Valgrid is limited or gimic compiled with ``-g``?

**Comment by bast** [comment]
Perhaps the most convenient would be to add a debug build to the matrix: https://github.com/qmcurrents/gimic/blob/master/.travis.yml#L7 and this debug build would run Valgrind.

**Comment by mariavd** [comment]
My master branch is behind upstream. What is the correct way to update it without causing a mess again with merge commits? I was testing things out today but I'm not completely done yet. I have a free afternoon tomorrow, so I can hopefully finish the test.

**Comment by bast** [comment]
https://coderefinery.github.io/git-collaborative/03-distributed/#shorter-route

**Comment by mariavd** [comment]
Thanks, no more messes from now on.

**Comment by mariavd** [comment]
The test is taking much longer than ordinary calculations. Do we want to check whether the integrated value is correct or simply run the minimum number of grid points, ignoring the wrong output? The latter is enough to check for memory leaks.

**Comment by bast** [comment]
For Valgrind we should create a super small example, only few grid points. The result should still be correct but it does not have to be physically useful.
