### ISSUE TITLE
divergence modul not working

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#117]
We have an old divergence module, which is not working. I tried to search the error and saw that for some reason needed basis and molecule information is not accessible. This error seems not to be new because the program has a stop statement.

**Comment by heikef** [comment]
The divergence is numerically calculated using a 5 point formula.

**Comment by heikef** [comment]
I suggest to remove this module from the code, since it does not work and nobody seems to use it. We could calculate the divergence at another point in the code or later on reintroduce the module. Thanks to git nothing should get lost.

**Comment by heikef** [comment]
I put this on my to do list, it should be rather fast to get rid of none used code.

**Comment by bast** [comment]
If it's broken, then I agree.

**Comment by heikef** [comment]
I tried several times and did not manage to use it. Then as commented above I localized the problem. This needs more work to be fixed. The program contains a hard stop statement, so somebody else knew about this issue as well.

**Comment by heikef** [comment]
I hate removing things, remember I dislike other people removing things from gimic, so I have to do it myself...
