### ISSUE TITLE
edens module not working

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#118]
We have an edens module, but it is a) not working and b) we have not documentation on how it should work. We should figure out on how this works and decide if we need it or if we prefer to replace it with a new module.

**Comment by heikef** [comment]
It would also be possible to calculate the electron density when the current density is set up. We could do this in one step. We should decide at one point if we really need an extra module. However, for future usage an extra module would allow an extension to analyze the electron density as well, assuming we want this at one point.

**Comment by heikef** [comment]
Since nobody seems to have strong feelings about this I suggest to remove the edens module and reintroduce it later on if needed be.

**Comment by bast** [comment]
If it's broken, let's get rid of it.

**Comment by heikef** [comment]
Yes, albeit it always feels bad to remove something from gimic...

**Comment by bast** [comment]
It will remain in our memories. And in Git history.

**Comment by heikef** [comment]
So be it. :)
