### ISSUE TITLE
linking issue with ifort

### ISSUE THREAD

**Issue by lnw** [qmcurrents/gimic#119]
When I try to compile gimic on taito (Finnish cluster),

module purge
module load python-env/intelpython2.7 cmake intel
./setup --fc ifort --cc icc --cxx icpc mybuild-i; cd mybuild-i
make

I get the following linking error:

[100%] Linking CXX executable gimic.bin
/usr/lib/../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
make[2]: *** [src/fgimic/gimic.bin] Error 1
make[1]: *** [src/fgimic/CMakeFiles/gimic.bin.dir/all] Error 2
make: *** [all] Error 2

Does that look familiar in any way?  Replacing ifort with gfortran and loading the respective module works without any errors.

cheers, lukas

**Comment by bast** [comment]
I will try to reproduce this.

**Comment by bast** [comment]
Confirmed.

**Comment by bast** [comment]
PR sent.

**Comment by lnw** [comment]
That was quick, thank you! (and I confirmed the fix)
