### ISSUE TITLE
QCTools not copied to the installation directory

### ISSUE THREAD

**Issue by mariavd** [qmcurrents/gimic#122]
Turbo2gimic.py needs functions defined in QCTools, which is located in the `tools/` directory. At the moment one needs to copy the folder manually to `bin/` in order to generate the input files from Turbomole calculations. Maybe the setup should handle this.

**Comment by heikef** [comment]
Thank you, we will put this on the to do list. @bast was working on the setup. Hope it is ok to assign him.

**Comment by bast** [comment]
Yes - but I really prefer if people self-assign. For me, assigning does not mean that somebody will work on it but that somebody is working on it. But it is OK to leave this one as it is.

**Comment by heikef** [comment]
@bast My apologies,  I note it for the future. Thanks for taking the issue.
