### ISSUE TITLE
Main equation could/should be part of the web documentation

### ISSUE THREAD

**Issue by bast** [qmcurrents/gimic#126]
@heikef it would be wonderful if you could put the main equation for the current density on the web documentation. The documentation understands LaTeX notation. I think this would be really valuable and show what exactly the code is doing.

**Comment by heikef** [comment]
From the publication in 2004 it should be clear what the code is doing but I can add the equations needed into the documentation. It is easier to click on the docu than to download and read a full paper.

**Comment by bast** [comment]
Already the one equation will help. No need to replicate everything but the one current density (tensor) equation.

**Comment by heikef** [comment]
Sure. That was my plan. I will also add the equation used for the ACID model.

**Comment by heikef** [comment]
the command ..math: does not work - is there something extra to install to visualize formulas with sphinx? 
http://www.sphinx-doc.org/en/stable/ext/math.html#module-sphinx.ext.mathbase

..image: imagefile.jpg - does also not work - online documentation is also not helpful -

**Comment by bast** [comment]
You need mathjax, like here: https://github.com/dftlibs/xcint/blob/master/doc/conf.py#L28

**Comment by heikef** [comment]
Thanks. I knew that I probably need this but the documentation did not tell how to include it. Your hint was very helpful. However, the fonts are a mess and I do not have a reasonable formula yet. I will continue working on it.

**Comment by heikef** [comment]
I would expect this to work: https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference

but for some reason I have to use \\tau instead of \tau for the greek letter tau

**Comment by bast** [comment]
I don't understand: "\tau instead of \tau"?

**Comment by heikef** [comment]
no \\\tau instead of \tau - I have to use for every command two times \ thus \\

**Comment by bast** [comment]
You do realize that they look the same in this discussion, right? But as to the math, whatever works is fine.

**Comment by heikef** [comment]
Here I have to type \\\ (three times \) that two times \ appears - that is the reason

**Comment by bast** [comment]
Or you protect them like here `\\`.

**Comment by heikef** [comment]
`\\`

**Comment by bast** [comment]
Nope, back-ticks.

**Comment by heikef** [comment]
This is unpractical, but thanks for showing on how to protect stuff.

**Comment by bast** [comment]
It's markdown markup for code blocks.
