### ISSUE TITLE
improvements for interactive scripts

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#137]
@mariavd Thank you for sharing your scripts! As promised I continue testing. There are two smaller things that you might want to change at one point. 

1. revcurrent was not working for me until I used:
`alias` revcurrent="mv current_profile.dat current_profile.dat.1 && awk '{printf \"%.6f\t%.6f\t%.6f\t%.6f\n\", \$1, -\$2, -\$4, -\$3}' current_profile.dat.1 > current_profile.dat"``

2. it would be useful to have a default at the end for the time
`Do` you accept duration= ?
Press [n] to change
n``

3. The automatic visualization of the plane does not work for me on the cluster for some reason. 
However, this is minor and probably related to our cluster.

**Comment by mariavd** [comment]
The automatic visuallization is hard to resolve if you are not able to open VMD through X-forwarding. I suggest that you ``scp`` the created ``xyz`` file and preview it locally.
