### ISSUE TITLE
Remove calculation of cube type files

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#138]
I think it is enough to calculate vti files, since we decided to go for Paraview. After a rather long testing period we know that vti related visualizations are working. Thus, we could remove the cube files since they are obsolete.

**Comment by heikef** [comment]
I can take care of this.

**Comment by bast** [comment]
I think cubes will be nice for scalar densities but we can reintroduce them then.

**Comment by heikef** [comment]
Scalar densities are also doable with vti - see ACID implementation. (assuming you mean something similar to the electron density)

**Comment by bast** [comment]
I know but then you need to install paraview etc. It's nice to look at cube files with avogadro or molekel or molden or gaussview. But I am perfectly fine if they go now.

**Comment by heikef** [comment]
Actually it would be great to collect all information on a vti / VTK type file including the molecular geometry, current density, modulus, ACID and other type of information. I did not figure out yet on how it works to put all on a vti file, but that is the way to go in the long run from my point of view.

**Comment by heikef** [comment]
Paraview is freely available - all open source.

**Comment by heikef** [comment]
We could later on consider adding a flag to the input file and let the user decide in which format he/she wishes the output to be.

**Comment by bast** [comment]
Sure, but not a lightweight to install always.

**Comment by heikef** [comment]
Paraview installation is no problem under Mac and Unix, about Windows I do not know, Maria could test.

**Comment by bast** [comment]
As I said, I am fine with removing cube file support. I can reintroduce it later once I need it.

**Comment by heikef** [comment]
Ok, then I will remove it. In case you need to reintroduce it I am sure this can be done in a more elegant manner. While working on this I realized that the edens module is also not working. I am tempted to remove the file.

**Comment by heikef** [comment]
The acid.txt file is also not needed any more from my point of view. We know the method does not work well - so no need for 2D integration or 2D poor man visualization of this. I will remove it.
