### ISSUE TITLE
link BLAS and LAPACK to gimic

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#141]
I think this is not done yet. Please correct me if I am wrong @bast Eventually you have already done this when changing the cmake stuff. Otherwise this is an issue. I would be great to be able to use blas and lapack.

**Comment by bast** [comment]
I guess I am not sure what this issue means. Are we using BLAS/LAPACK in the code?

**Comment by heikef** [comment]
We are not using it because we can not.

**Comment by bast** [comment]
What would we like to use it for?

**Comment by heikef** [comment]
Diagonalization of a matrix.

**Comment by heikef** [comment]
In general when trying to make things more efficient it is good to use blas/lapack, so if it is possible for us to get access to it why not use it?

**Comment by bast** [comment]
Sure. I just wanted to make sure we know why we want to link to it. Now we know.
