### ISSUE TITLE
Stop printing txt files to save time and to have less output files

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#151]
I suggest to remove the print out for txt files, since we moved to vtk visualization. For debugging purpose they might still be useful, so we keep them but do not print them for all calculations, which probably saves some time. 
An exception is the jmod.txt file when integrating over a bond. Here a quick gnuplot visualization of the jmod.txt file helps to make sure that the integration plane is properly set up and should therefore be kept. 
I am currently working on this and will also adapt the test cases we have.

**Comment by bast** [comment]
I personally like the txt files since they don't bind you to a specific visualization tool. Is the extra time really significant?

**Comment by bast** [comment]
Instead of removing the print I would either make it possible to turn it off or turn it on.

**Comment by heikef** [comment]
I introduced a "debug" flag so the *.txt files remain accessible any time. Thanks to git nothing is really lost.

**Comment by heikef** [comment]
The main problem are the 3D calculations, here jvec information on a txt file leads to horrible visualizations and is basically not needed any more. If we want to go for other visualization tools this is no problem. Eventually we can move back at one point when we have better grids.
