### ISSUE TITLE
check Turbomole basis set ordering

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#154]
At one point we should add a check to make sure that we do not run into problems with the Turbomole ordering of polarization functions. Gimic expects proper s,p,d,f.... ordering while Turbomole sometimes puts the polarization functions at the end of the basis file thus having s,p,d,p,f,g ordering, which we do not want. 
Eventually this is just a small modification of the turbo2gimic.py script.

**Comment by mariavd** [comment]
As far as I see it's not so straightforward because there are just numbers in the CAODENS and XCAODENS files. Who has done the interface from Turbomole to Gimic - not ``turbo2gimic.py`` but the Turbomole module? Probably the solution is there.

**Comment by heikef** [comment]
The only solution we have for the moment is to change the basis file by hand before doing a dscf run followed by mpshift. Comparison with a non modified scf run confirms that everything is ok. 

But via turbo2gimic.py it could be detected and a warning could be written out. Then the user knows where the problem is localized.

**Comment by mariavd** [comment]
Well, writing a warning is simple enough - ``turbo2gimic.py`` will just parse the ``basis`` file but it's not a solution to the problem. Ideally the presence of the ``$gimic`` keyword in the ``coord`` file should signal to Turbomole to reorder the basis functions before running mpshift. If we change the basis order without re-running mpshift, then it's useless. 

Or did you mean that Gimic expecting the basis functions to be in the correct order should be fixed, so that it doesn't mind if they are s, p, d, p, f?

**Comment by heikef** [comment]
They know about the problem. We reported it, but it is understandable that they hesitate to change their basis set structure based on the needs of our program.

**Comment by mariavd** [comment]
So is it the latter half of my reply that you are after?

**Comment by heikef** [comment]
A simple solution would be to print out a warning for the user in the turbo2gimic.py script. A more complicated solution would be to reorder the basis functions inside gimic. This is independent of the mpshift run as long as we know the Turbomole basis ordering and the gimic one. I am not sure if this answers your question.

**Comment by bast** [comment]
I think GIMIC should use only one basis set ordering. Other codes might and will use other ordering but then this should be reordered outside. We should not compensate for other codes inside GIMIC. We should document one consistent API and other codes have to deal with it :-)

**Comment by mariavd** [comment]
Well, my question basically is if we want just a warning message or some action taken hidden from the user.

**Comment by heikef** [comment]
We depend on input information from other codes. This is something to keep in mind. I would also prefer not to touch the gimic basis routines. -))

**Comment by heikef** [comment]
I think for the time being we are converging to a warning for the user.

**Comment by mariavd** [comment]
Ok, so the task is getting clearer. I will take a look how to get it done.

**Comment by mariavd** [comment]
I agree, that we want to have our own ordering, which is s, p, d, f, g... As to other codes, I still feel that the Turbomole part should get a fix - if the $gimic keyword signals reordering of the basis functions, then it's problem solved. And this apparently doesn't mean that they need to restructure their own code but add an extra routine which is called when the keyword is in the control file.

**Comment by heikef** [comment]
Contact the Turbomole support and tell.
