### ISSUE TITLE
Placement of integration plane not clear in documentation

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#155]
I got feedback from a new gimic user. Apparently the setup of the integration plane for running a gimic calculation is not clear enough. I suggest to improve the documentation. Perhaps a picture is helpful in this context.

**Comment by mariavd** [comment]
I have a picture to illustrate it. Should I commit it in my ``docs`` branch?

**Comment by heikef** [comment]
I suggest to make a new branch commit the pic and file a pull request.

**Comment by bast** [comment]
Yes. Then we can see and discuss the pic before it goes in.

**Comment by heikef** [comment]
You can easily delete obsolete branches on your fork on github. So no harm is done by setting up a new feature branch add small changes and file a pull request. This keeps things more structured and it is easier to review compared to master.
