### ISSUE TITLE
Discussion on height / width versus in /out/up/down keywords

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#159]
I open this issue after a discussion with @mariavd Perhaps you want to take over here and describe the issue?

**Comment by mariavd** [comment]
It was a question, not an issue. I just wanted to know if you prefer to see the input variables in the script as:

down = 10, up = 10
or
down - 10, up = 10

**Comment by heikef** [comment]
Ok, sorry I misunderstood. I think for the scripts only positive values are fine. I will close the issue then since it was no issue. -))
