### ISSUE TITLE
Command-line arguments

### ISSUE THREAD

**Issue by mariavd** [qmcurrents/gimic#163]
This will sound critical, so my apologies. I just wanted to summarise. It seems that some of the command-line arguments are not working properly. 

```
$ gimic -h
usage: gimic [-h] [-t TITLE] [-b {pygimic,fgimic,london,gimlet}] [-d DEBUG]
             [-o OUTFILE] [-D DEBUG_FILE] [-v] [-q] [-y]
             [file]
```

Help, title and dry run work fine. Debug level is fine but the option to print a debug file is not working:
```
$ gimic gimic.inp -D gimic.dbg
Traceback (most recent call last):
  File "/homeappl/home/mariavd/appl_taito/gimic/build/bin/gimic", line 303, in <module>
    main()
  File "/homeappl/home/mariavd/appl_taito/gimic/build/bin/gimic", line 27, in main
    inkeys = parse_keywords(args)
  File "/homeappl/home/mariavd/appl_taito/gimic/build/bin/gimic", line 149, in parse_keywords
    inkw.setkw('debug_file', args.debugf)
AttributeError: 'Namespace' object has no attribute 'debugf'
```

Maybe a debug file is not needed? 

Verbose ``-v`` and quiet ``-q`` don't print anything in addition to or less the usual output. 

As to the backend option, what is it supposed to mean?

**Comment by heikef** [comment]
Thank you for pointing this out! We will put it on our to do list.

**Comment by heikef** [comment]
Also critical feedback is appreciated. :)

**Comment by bast** [comment]
As to backends: we always run with fgimic. There are other backends in the works but I am not sure these ever got finished. For sure they are untested. If an option is never used, not working, and not even clear what it should do, I think we should remove it.

**Comment by heikef** [comment]
I think pygimic and gimlet were working at one point. London never worked, because that interface got never finished. For the time being we can remove this, because currently we only use fgimic. This makes also the life of the user easier. Thanks to git the structure will not get lost and we can reactivate it if needed be.

**Comment by mariavd** [comment]
Are you aware how is the London interface supposed to work? In London the orbitals are complex.

**Comment by heikef** [comment]
I know that in London orbitals are complex, but I remember that Jonas and Erik were talking about an interface. I think the idea was to read in the current density from London and use the analysis tools from gimic. Then it should not matter if orbitals are complex or not.

**Comment by heikef** [comment]
pygimic was in construction - there is a lot available - I am not sure if we want to delete all of this

**Comment by bast** [comment]
I would leave pygimic until we have a new Python interface. But I would remove the other broken flags.

**Comment by heikef** [comment]
The plan is to make gimlet work. Partly it is or has been at least working. Jonas probably knows.

**Comment by bast** [comment]
What is it even?

**Comment by heikef** [comment]
It allowed to calculate currents in mrchem as far as I remember.

**Comment by heikef** [comment]
we do not have a library for it - I can remove it from the gimic run script - in case we need it later on we can re-add it

**Comment by heikef** [comment]
After some archeology I found the gimlet directory. Filled but no green light for sharing. Therefore it is not here.
