### ISSUE TITLE
Restore OpenMP parallelization

### ISSUE THREAD

**Issue by bast** [qmcurrents/gimic#168]
Currently all tests pass using OpenMP when compiled without optimization.

With optimization the following test fails:
- benzene/integration

**Comment by bast** [comment]
Investigating ...

**Comment by bast** [comment]
Running http://valgrind.org/docs/manual/hg-manual.html to investigate data races.

**Comment by bast** [comment]
Indeed helgrind indicates data races. Trying to locate them.

**Comment by bast** [comment]
Good progress on the OpenMP front. Seems to work. I will do a bit more testing, benchmarking, and documentation and submit a PR soon.

**Comment by heikef** [comment]
Great!

**Comment by bast** [comment]
Timings with GNU compilers ...

TZ benzene:
- sequential: 1m30s
- OpenMP (20 cores): 9.5s

QZ benzene:
- sequential: 8m30s
- OpenMP (20 cores): 36s
