### ISSUE TITLE
Valgrind tests are failing on Stallo

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#172]
I have loaded the following modules on Stallo as recomended in the manual: 
module load Python/2.7.12-foss-2016b
module load CMake/3.7.2-foss-2016b
module load Valgrind --> which gives Valgrind/3.11.0

./setup --omp --blas 
cd build
make -j20 ; make install; make test

leads to:

The following tests FAILED:
	 22 - benzene/valgrind-integral (Failed)
	 23 - benzene/valgrind-2d (Failed)
Errors while running CTest

Any idea why the new Valgrind tests fail? 

module list tells:

Currently Loaded Modules:
  1) StdEnv                                                   (S)
  2) gold/2.1.5.0                                             (S)
  3) intel/13.0
  4) imkl/11.0.0
  5) StdMod
  6) bzip2/1.0.6-foss-2016b
  7) zlib/1.2.8-foss-2016b
  8) ncurses/6.0-foss-2016b
  9) libreadline/6.3-foss-2016b
 10) Tcl/8.6.5-foss-2016b
 11) SQLite/3.13.0-foss-2016b
 12) Tk/8.6.5-foss-2016b
 13) GMP/6.1.1-foss-2016b
 14) libffi/3.2.1-foss-2016b
 15) Python/2.7.12-foss-2016b
 16) GCCcore/5.4.0
 17) binutils/2.26-GCCcore-5.4.0
 18) numactl/2.0.11-GCC-5.4.0-2.26
 19) hwloc/1.11.3-GCC-5.4.0-2.26
 20) GCC/5.4.0-2.26
 21) OpenMPI/1.10.3-GCC-5.4.0-2.26
 22) FFTW/3.3.4-gompi-2016b
 23) gompi/2016b
 24) OpenBLAS/0.2.18-GCC-5.4.0-2.26-LAPACK-3.6.1
 25) ScaLAPACK/2.0.2-gompi-2016b-OpenBLAS-0.2.18-LAPACK-3.6.1
 26) CMake/3.7.2-foss-2016b
 27) Valgrind/3.11.0

most of them are the default modules - only the three I listed above are newly loaded.

**Comment by heikef** [comment]
Maybe I am doing something wrong? Have to use a special compiler flag? If yes, please let me know and document this also for other gimic users.

**Comment by bast** [comment]
I don't think you do anything wrong. Can you have a look why they fail? Look for the generated diffs/logs.

**Comment by heikef** [comment]
ERROR: extracted sizes do not match
own gave 1 numbers:
==57703==     in use at exit: 86,208 bytes in 20 blocks

reference gave 2 numbers:
==30761==     in use at exit: 0 bytes in 0 blocks


.       ==57703== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 5 from 5)ERROR                            # expected: 0
ERROR                            # expected: 0
ERROR     # expected: 0

**Comment by heikef** [comment]
ERROR: extracted sizes do not match
own gave 1 numbers:
==50784==     in use at exit: 86,208 bytes in 20 blocks

reference gave 2 numbers:
==30761==     in use at exit: 0 bytes in 0 blocks


.       ==50784== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 5 from 5)ERROR                            # expected: 0
ERROR                            # expected: 0
ERROR     # expected: 0

**Comment by heikef** [comment]
both diff logs look similar - I guess this is a good sign

**Comment by bast** [comment]
It means there is probably a memory leak.

**Comment by heikef** [comment]
Hm, is this Stallo specific? The default should not be that two tests fail.

**Comment by bast** [comment]
But what you have tested is not part of automated tests either. It should be(come) but I am not surprised that you found this.

**Comment by heikef** [comment]
So these two tests are expected to fail?

**Comment by bast** [comment]
No. They have possibly just never been tested in the context that you have tested them in.

**Comment by heikef** [comment]
OK, that means I can not do something about this right now.

**Comment by bast** [comment]
Well you can. You can either debug this or somebody else will sooner or later :-)

**Comment by heikef** [comment]
On that machine it could be anything. :)

**Comment by bast** [comment]
It is most likely a bug in the code. In this case probably non-critical since results are correct but memory is not fully released: a memory leak is probably present.

**Comment by heikef** [comment]
The valgrind output is huge and cryptic. This does not make sense to me. How can one possibly spot something there?

**Comment by bast** [comment]
Start from the end.

**Comment by heikef** [comment]
There is no name related to any of the gimic subroutines.

**Comment by mariavd** [comment]
@heikef You can send me the output from valgrind and I will investigate the problem.

**Comment by heikef** [comment]
@mariavd Thank you for your offer! I will contact you via email.

**Comment by bast** [comment]
I will look at it - I anyway want to reactivate Intel on Stallo (currently crashes) so that we can use MKL.

**Comment by bast** [comment]
And I hope you are never running `make -j20` on Stallo login node :-)

**Comment by bast** [comment]
Note that this test also fails without `--omp --blas`. When you observe an issue always first try to isolate it by removing degrees of freedom.

**Comment by bast** [comment]
On Stallo Valgrind indicates memory leaks but these seem outside of GIMIC. My recommendation is to not worry about it at the moment. We could also consider taking Valgrind tests outside of standard test set and only run them on Travis?

**Comment by heikef** [comment]
I knew that it also fails when removing --omp and --blas but did not report because I thought that this is not related to each other.

**Comment by heikef** [comment]
Another thing is that I was not using ifort but gfortran.

**Comment by bast** [comment]
The compiler part was clear but next time please indicate that the flags don't matter since it looked initially like there is a problem with the flags suddenly.

**Comment by heikef** [comment]
As commented before: for a new user it might be irritating that some tests always fail. We could check on a standart ubuntu environment if valgrind also fails. If yes it might be a good option to get rid of these tests and only test under travis, which is for developers only. On the other hand when trying to identify a leakage it might be useful to have these tests also under the standard version distributed for all user available.

**Comment by bast** [comment]
Travis is Ubuntu. I think we should take the test out for users who just want to compile the code.

**Comment by bast** [comment]
This test is really only for developers in my opinion.

**Comment by heikef** [comment]
How can we do this? The developers should have access to the tests. But having too many branches might also not be an optimal solution. I am sure there is a cmake trick for this. Do you have an idea?

**Comment by bast** [comment]
We do this with a CMake option that can be turned on or off and by default is off.

**Comment by heikef** [comment]
Good idea!

**Comment by heikef** [comment]
Can we close this issue? The on of option in cmake has been added.

**Comment by bast** [comment]
Agree - this was solved in 3ec38a2e26da427601ef79d757ffebfccee15307.
