### ISSUE TITLE
Intel compiled build crashes on Stallo

### ISSUE THREAD

**Issue by bast** [qmcurrents/gimic#174]
At this moment I have no idea why. More details to come.

**Comment by bast** [comment]
Debug build seems to run fine. Now having a closer look at optimized build.

**Comment by bast** [comment]
Only some tests fail so it is not a general issue.

**Comment by heikef** [comment]
Do we have an explanation?

**Comment by bast** [comment]
Not yet ...

**Comment by bast** [comment]
I have identified two issues:
- in test c4h4/read-grid there is a divide by zero in https://github.com/qmcurrents/gimic/blob/master/src/fgimic/vtkplot.f90#L110
- down_length/out_length can be undefined (e.g. benzene/vectors): https://github.com/qmcurrents/gimic/blob/master/src/fgimic/grid.f90#L108-L109

**Comment by bast** [comment]
Unassigned myself ...

**Comment by mariavd** [comment]
@bast Are you sure that down_length/out_length can be undefined? It is true that they are not initialized but they seem to take a value in the if or the else statements. The value is used only afterwards. I'm sorry if I'm being blind.

**Comment by bast** [comment]
But they only take the value if these are specified in the input. What if nothing is in the input? Then they are undefined. Depending on the compiler it can be zero or a fantasy number. You can see this by compiling with `-trapuv` with Intel. This flag initializes all variables to crazy numbers which is a good test to see whether the code initializes them to something sane.

**Comment by heikef** [comment]
Not sure if this is helpful but when loading imkl/2017.3.196-iimpi-2017b it is possible to compile the code. I used the suggested options for the setup. 
./setup --fc=ifort --cc=icc --cxx=icpc --cmake-options="-D ENABLE_MKL_FLAG=ON"

**Comment by bast** [comment]
Well I managed to compile the code but it crashes then and the issues are linked above.

**Comment by heikef** [comment]
For me it crashed at another point.

**Comment by bast** [comment]
At which point did it crash for you?

**Comment by heikef** [comment]
In jmod2_vtkplot.

**Comment by heikef** [comment]
benzene/3d test crashed - after my "clean up" it crashes as well when compiling with gfortran. :)

**Comment by heikef** [comment]
The benzene/3D test runs through when switching acid=off. Then jmod.vti and jvec.vti are created and correct compared to the reference we have. This looks like an address error but the question is where? Switching acid=on the test provides the correct acid.vti file but crashes before jmod.vti and jvec.vti are calculated. 
I had a look at the routines and my impression is that it must be related with the pointer to jtens.

**Comment by bast** [comment]
Thanks for the new leads! I will try to investigate this very soon.

**Comment by heikef** [comment]
If it is indeed related to the acid module I feel responsible....

**Comment by bast** [comment]
But do you feel you have the tools and time to find the problem or should I have a look?

**Comment by heikef** [comment]
Please have also a look. My impression is that this problem is related to object oriented Fortran. Maybe you have an advise. Since I do not spot the possible error, which only occurs with this intel compiler I will as a next step print out as much as possible to get an idea on where something goes wrong.

**Comment by heikef** [comment]
This issue is very old. I am closing it. We can reopen it if needed be.
