### ISSUE TITLE
Pictures in documentation missing! 

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#185]
The pictures showing the keywords for the integration plane dimensions are not in the documentation
any more. They would make sense to be added in the grid section. I do not recall when and where they got "lost". They are in the documentation directory but are not part of the *.rst files any more.

**Comment by mariavd** [comment]
I will fix it this week. I have been working on expanding the interpretation of results.

**Comment by heikef** [comment]
Great! Thanks!

**Comment by heikef** [comment]
Has this been fixed?

**Comment by mariavd** [comment]
I'm sorry, I hasn't been. I admit I forgot. Can I have some time extension? Or I could ask for a merge request for my incomplete guide. It should be better than nothing for now. 

https://github.com/mariavd/gimic/blob/docs/doc/interpretation.rst

**Comment by heikef** [comment]
No problem. An improved documentation albeit not complete ready is better than what we currently have. Please file a pull request when you find time and thanks for all the work!

**Comment by mariavd** [comment]
@heikef I vaguely followed your discussion in the other issues. So the in/out, up/down are removed - which is good in my opinion. How do you prefer that I modify the labels on the picture of the plane at the documentation page I linked to above? They should be width and height but still somehow specify that width[0] is the distance from one of the integration plane to the bond with negative sign, and width[1] is the distance from the other end of the integration plane to the bond?

**Comment by heikef** [comment]
@mariavd Thanks for pointing this out. A pragmatic solution would be to keep the picture as it is and add the rest of the information into the figure caption.
