### ISSUE TITLE
Memory allocation checks

### ISSUE THREAD

**Issue by mariavd** [qmcurrents/gimic#19]
I noticed that there is a tendency not to check whether memory has been allocated in many places of the code. When we want to handle large molecules this might lead to segmentation faults. Do you think they should be introduced at least in places where large arrays are being allocated?

**Comment by bast** [comment]
I think this is in principle a good idea. But how do you want to do that?

**Comment by mariavd** [comment]
I have seen this example:


!Some part of the code determines nmax
allocate(array(nmax),stat=error)
if (stat.ne.0) then
print*,'error: couldn't allocate memory for array, nmax=',nmax
stop
endif

At least in C I would define a function to allocate an array of given size, and do the check whether the pointer exists, so maybe I can do the same in Fortran?

________________________________

**Comment by bast** [comment]
My question is whether you will ever see the error messages. If allocation fails, you may never return to print what happened. Try it out on a small example with a gigantic allocation.

**Comment by mariavd** [comment]
I see. I tried allocating 10 billion elements in an integer array and gfortran gave the message:
Operating system error: Cannot allocate memory
Allocation would exceed memory limit

In C the same produces a seg fault - tested it, too. Alright, so I just need to switch to Fortran way of thinking.

**Comment by bast** [comment]
What I think is far more useful in practice is a memory-dry run option where one can run through the calc without computing anything only allocating and deallocating.

**Comment by mariavd** [comment]
Yes, this makes sense. I will now close the issue.
