### ISSUE TITLE
3D-LIC.pvsm file missing

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#190]
Got user feedback that the Paraview 3D-LIC.pvsm file is missing and did not find it either. It looks as during work on documentation something perhaps got lost. @mariavd would you mind to have a look at this? Thank you. 

http://gimic.readthedocs.io/en/latest/scripts.html#some-tips-and-advice

**Comment by mariavd** [comment]
I will

**Comment by heikef** [comment]
Thank you!
