### ISSUE TITLE
Release notes // What's new

### ISSUE THREAD

**Issue by mariavd** [qmcurrents/gimic#192]
I think it might be handy to keep some release notes to list what features have been added. I almost missed to notice that @heikef had added jmod=off. What do you think?

**Comment by heikef** [comment]
The idea with the mailing list was very nice.

**Comment by heikef** [comment]
General release notes are also a good idea. We should also discuss about having a new release published at one point.

**Comment by mariavd** [comment]
I have made a Gmail account in order to use YouTube. Possibly it can be used to spread news to the not-that-many of us? I can give you the password.

**Comment by bast** [comment]
Yes very good suggestion - I think we should track release notes in this repo under the documentation.

**Comment by heikef** [comment]
Since nothing happened here, I will close the issue. We can reopen it if needed be.
