### ISSUE TITLE
Even "drier" dry run

### ISSUE THREAD

**Issue by mariavd** [qmcurrents/gimic#193]
When one handles complicated molecules it is necessary to preview the integration plane, sometimes more than a couple times. This only requires the grid to be defined. In a huge molecule of some 800 atoms and more this means at least 15 minutes. Currently, gimic reads in both the basis and the density matrices and transforms the orbitals, and only afterwards allocates the grid. 

@lnw suggested a reasonable idea that an "extra dry" is made, where only the MOL data is read in and the density matrix data is not touched at all. If you approve of the idea, I can take care if it.

**Comment by heikef** [comment]
Are information about the basis sets needed for the grid set up?

**Comment by lnw** [comment]
The grid generation should require purely geometrical data only.
I was of course joking about the 'super-dry' run, maybe a useful argument name would be '--generate-grid'.  I would expect such a run to return in less than a second, anything else is not justified.

**Comment by bast** [comment]
I agree, if grid generation takes more than 2 seconds, something is not right.

**Comment by lnw** [comment]
So we agree, that a '--generate-grid' option which does nothing else would be helpful?

**Comment by bast** [comment]
Yes I think this would be helpful.

**Comment by heikef** [comment]
I think it would make more sense to replace the old "dryrun" option with this new option we are discussing. All a user needs when doing a dryrun is the placement of the integration plane, which
depends on the grid. Instead of introducing the "generate-grid" option we could keep the dryrun option and modify it.
