### ISSUE TITLE
grid options that are not implemented

### ISSUE THREAD

**Issue by lnw** [qmcurrents/gimic#201]
In the documentation, it says that a bond grid can be specified by the four keywords in/out/up/down (as an alternative to width/height). This is not implemented.

In the documentation, it also says that a lobatto-type grid can be chosen.  This also throws an error, although it looks like it's almost implemented.  Adding a case at around fgimic/grid.f90/120 + testing might be enough.

Should these options be removed from the manual or added to the code?

**Comment by heikef** [comment]
This sounds strange. The in/out/up/down options should work. Maria is using them for her bash scripts. 
The program uses gauss-lobatto. Which keyword did you use? I am a bit surprised because this grid is part of the test suite examples. So it should work.

**Comment by lnw** [comment]
Maria's scripts use in/out/up/down as input but output height and width.

There is a function to create a lobatto grid, but in some places the choice hardcoded to gauss, and in other places it accepts an option but lobatto is not one of them. If you grep the test-folder for 'type=', you'll only find 'even' and 'gauss'.  So, type=lobatto is not tested and it doesn't work.

The question is: should the code or the documentation be changed?

**Comment by heikef** [comment]
Ok, then we leave things as they are and remove the keywords in/out/up/down from the documentation. 
Yes, type "lobatto" is never tested because type "gauss" stands for Gauss-Lobatto as far as I remember. We can tell this in the documentation. Do you want to fix this?

**Comment by lnw** [comment]
If I read the code correctly, 'gauss' gives you a gauss-grid, not a gauss-lobatto-grid.  I wonder whether there are problems with the Gauss-Lobatto implementation, or if someone just lost interest.  In the former case, the dead code can be removed, in the latter case a few more lines would enable that feature.

**Comment by heikef** [comment]
Hard to tell. Jonas would probably know.

**Comment by bast** [comment]
I was always under the impression that GIMIC uses Gauss-Lobatto. But this can be verified. I have another implementation of the Gauss-Lobatto grid (in DIRAC) and we could compare.

**Comment by lnw** [comment]
I think when you look at src/libgimic/gaussint.f90 it's rather obvious that 'gaussl' generates a Gauss grid and 'lobattomy' generates a Gauss-Lobatto grid (you can see that lobattomy sets the first and last point to the intervall boundaries, while gaussl does not).  From there it's only two or three steps to verify that you never get a Gauss-Lobatto grid, because lobattomy can never be called.

So, should those input options be removed from the documentation or added to the implementation?

**Comment by bast** [comment]
I think in this case added to the implementation.

**Comment by heikef** [comment]
I think the in/out and so on thing is something different. It has historic reasons that this has been removed from the code but not from the documentation. I think some people prefer this input over the height and witdth. However, for the time being it is ok to remove it from the documentation since it is not longer supported. 

The other thing is the gauss-lobatto and gauss stuff. This is surprising to me. I thought it has always been the gauss-lobatto stuff as reported in the 2004 paper. The situation Lukas identified might also have historic reasons. I do not know more details about this. I agree that this should be fixed.
