### ISSUE TITLE
configuration fails if git is present but the directory is not under version control

### ISSUE THREAD

**Issue by lnw** [qmcurrents/gimic#204]
During the cmake configuration, there is a test if a git binary exists, and if so, the version of the current commit is retrieved.

However, it is perfectly possible to obtain the zipped project from github, so it is not under version control.  If during the configuration a git binary is found, the configuration fails.

**Comment by bast** [comment]
I will fix this - taking the issue.

**Comment by bast** [comment]
#205 solves it.
