### ISSUE TITLE
jmod skipped even without jmod=off specified

### ISSUE THREAD

**Issue by mariavd** [qmcurrents/gimic#207]
Maybe I'm stupid but when I tried including the  ``jmod=off`` keyword, gimic complains that it doesn't exist. So I put a comment as in the section:

```
Advanced {
    lip_order=5      # order of Lagrange Interpolating Polynominals to use
    spherical=off     # don't touch, unless you REALLY know what you are doing
    diamag=on           # turn on/off diamagnetic contributions
    paramag=on          # turn on/off paramagnetic contributions
    GIAO=on             # turn on/off GIAOs. Don't change unless you know why.
    screening=on        # use screening to speed up 
    screening_thrs=1.d-8   # Screening threshold
#jmod=off
}
```

But in the output file the modulus is still skipped. Effectively, this was my intention but is this normal behaviour? I can take a look if it's a bug, it is probably an if/else line.

**Comment by mariavd** [comment]
Also, the calculations suddenly turned out super fast - the result looks reasonable on a plot. I had 465 slices  and all the calculations finished in just 2 minutes... still sounds suspiscious. The molecule is toluene at B3LYP/def2-TZVP level. 

So... this is the number of grid points per slice:
```
 INFO: Adjusted number of grid points for quadrature:   648    9    0   
   Number of grid points <v1,v2>:  648    9    1   
   Total number of grid points  :      5832
```



The binary was compiled with 
```
./setup --omp --blas
```

All tests pass, appart from the reports by valgrind about compiler library issues. I honestly don't know what's going on. Benzene from the test cases is calculated correctly. What do you think?

**Comment by heikef** [comment]
jmod on/off should be in the Essential section and not in Advanced

**Comment by mariavd** [comment]
Right, my mistake regarding that. I appreciate it that by default jmod is off. 

What is your opinion on the surprisingly fast calculations?

**Comment by heikef** [comment]
Assuming that the results are correct I am of course happy to hear about the speed up. Improving the code and making it faster plus operating parallel is the big goal of our AUS project. Setting jmod=off per default avoids one extra integration run, which is not necessary. This adds on top to the openMP and BLAS extensions.

**Comment by heikef** [comment]
It would be great to get some timings to show the improvements. @bast and also myself would be super happy to see this. ;)

**Comment by lnw** [comment]
If it's definitely unreasonably fast, can you bisect?  With a two-minute-job that's not too bad ...

**Comment by heikef** [comment]
As I said, assuming that the results you obtain are correct.

**Comment by bast** [comment]
Interesting! Let me know if I should test something on my side.

**Comment by mariavd** [comment]
I have a porphyrin project to do, so I can make a summary of the timing with the latest vs an older version of gimic. I need to get it done like this or next week, so you will hear about it soon.

**Comment by heikef** [comment]
Since I did not hear something else I hope it is ok to close this issue.
