### ISSUE TITLE
Visualize acid and jmod using ParaView

### ISSUE THREAD

**Issue by EudesG** [qmcurrents/gimic#218]
How can i visualize the acid and jmol using ParaView?

**Comment by heikef** [comment]
There is an example in https://github.com/qmcurrents/gimic/tree/master/examples/benzene/3D
Please have also a look here: https://github.com/qmcurrents/gimic/issues/180

**Comment by heikef** [comment]
Note, we do not have the feature to visualize the current density on the chosen ACID surface.

**Comment by heikef** [comment]
Is this issue resolved?

**Comment by EudesG** [comment]
Yes, thank you!

**Comment by heikef** [comment]
Ok, thanks for letting me know. I will close the issue then.
