### ISSUE TITLE
If valgrind not installed, either do not fail or fail with an informative message

### ISSUE THREAD

**Issue by bast** [qmcurrents/gimic#219]
Otherwise it can look as if the code is not correctly installed.

**Comment by heikef** [comment]
Maybe cmake could check if Valgrind is installed and if not simply skip these tests?

**Comment by bast** [comment]
Yes, I agree. With some warning.

**Comment by heikef** [comment]
We could also remove the two Valgrind tests from the CMakeLists.txt file. Then they would not be used and would not irritate the user until we have fixed the issue. What do you think?

**Comment by bast** [comment]
I think even better is to make them non-default. On Travis we switch them actively on, but they are really only interesting during development and I agree that users should not be bothered with those.

**Comment by heikef** [comment]
How do we do this best? What do you recommend?

**Comment by bast** [comment]
I will send a fix.

**Comment by heikef** [comment]
Great! Thank you.
