### ISSUE TITLE
Unable to make 2D acid plot in Paraview

### ISSUE THREAD

**Issue by patrashantigopal** [qmcurrents/gimic#227]
Hi,

I am facing the following problem when I am trying to make a 2D acid plot using .pvsm and jvec.vti file in Paraview:

Generic Warning: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ServerManager\Core\vtkSMStateVersionController.cxx, line 621
The state file uses the old 'Glyph' filter implementation. The implementation has changed in ParaView 5.6. Consider replacing the Glyph filter with a new Glyph filter. The old implementation is still available as 'Glyph Legacy' and will be used for loading this state file.

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ClientServerCore\Rendering\vtkCompositeRepresentation.cxx, line 357
vtkPVCompositeRepresentation (0000024BBA8593E0): No representation was found with Name: Surface LIC

Warning: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ServerManager\Core\vtkSMProxy.cxx, line 853
vtkSMSourceProxy (0000024BB7DD30F0): Proxy (filters, GlyphLegacy)  has been deprecated in ParaView 5.6 and will be removed by ParaView 5.7. 
        It has been replaced by 'GlyphWithCustomSource'. Please consider using that instead.

I shall be very helpful if someone can help. All other plots are OK.

Best regards,
Shanti

**Comment by heikef** [comment]
The information about ACID is stored on acid.vti but this will not be generated when you do a 2D calculation. You have to do a 3D calculation and switch the flag acid=on. Then acid.vti will be generated and you can visualize it with Paraview as isosurface.

**Comment by patrashantigopal** [comment]
![jvec-2d-paraview](https://user-images.githubusercontent.com/46942514/55353307-9c1c0400-54e0-11e9-885a-7e852f70ec2c.jpg)

Please look at the attached file. I am unable to make this plot.

Some other points:

1) I saw a video in youtube uploaded by qmcurrents regarding the streamline plot. Can you please tell me about the use of this plot. It would be great if you can refer to a paper. 

2) How to get the value of current for a particular bond?

I appreciate and gratefully acknowledge all the help which I have received from bast, heikef and guacke in the process of learning gimic.

Best regards,
Shanti

**Comment by heikef** [comment]
The plot you are showing has been obtained using jvec.vti file. It is an overlay created with ParaView. You have create a slice and visualize this with the LIC plugin. Then you add the filter glyps and create the arrows. 
Alternatively you can do a 2D calculation and obtain the same plot but without adding a slice. 
Go to the examples directory. You can read in jvec-2d-paraview.pvsm file into ParaView. This should help you to see the filters, which have been applied.

**Comment by heikef** [comment]
Now to question 1, see above.  A good starting point to read about current densities is our review article: Wiley Interdisciplinary Reviews, 6, 639, (2016). There you find also other references.

**Comment by heikef** [comment]
Now to question 2; you need to integrate over the current flow across a bond to obtain the value you are after. Look for example into the examples/benzene/int directory. Read also the section in the documentation about the interpretation of calculated results. 
https://gimic.readthedocs.io/en/latest/interpretation.html

**Comment by patrashantigopal** [comment]
Dear Heikef,

Thank you for all your response. When I am copying the input from example/benzene section it is showing the following error:

This is F-GIMIC.

 ****************************************************************
 ***                                                          ***
 ***           GIMIC 2.1.4 ()                              ***
 ***              Written by Jonas Juselius                   ***
 ***                                                          ***
 ***  This software is copyright (c) 2003-2011 by             ***
 ***  Jonas Juselius,  University of Tromso.                  ***
 ***                                                          ***
 ***  You are free to distribute this software under the      ***
 ***  terms of the GNU General Public License                 ***
 ***                                                          ***
 ***  A Pretty Advanced 'Hello World!' Program                ***
 ****************************************************************

 Wed Apr  3 18:08:57 2019
  TITLE:

<<< ERROR: read_intgrl(): open failed. >>>

Whereas when I am running it by taking the input from build/test/benzene directory then it is working fine. But in this directory, I could not get the input file which will give the value for a bond. Looking forward to your answer.

Best regards,
Shanti

**Comment by heikef** [comment]
You need to have XDENS + MOL in the same directory.

**Comment by patrashantigopal** [comment]
I have the XDENS + MOL files in the directory. I am doing the other calculations in my system and I am getting nice results. I can now make jmod plot and isosurface acid plot also. But I am unable to get the value for a particular bond.

**Comment by patrashantigopal** [comment]
I think I understand the problem, input file tells the system it can find the files in the previous directory:

basis="../MOL"
xdens="../XDENS"

So I need to keep those files one step before the input directory.

**Comment by patrashantigopal** [comment]
Tomorrow I will try this way and let you know.

**Comment by patrashantigopal** [comment]
Now I can run. Please how to get the value of current for each bond in the output file:

This is F-GIMIC.

 ****************************************************************
 ***                                                          ***
 ***           GIMIC 2.1.4 ()                              ***
 ***              Written by Jonas Juselius                   ***
 ***                                                          ***
 ***  This software is copyright (c) 2003-2011 by             ***
 ***  Jonas Juselius,  University of Tromso.                  ***
 ***                                                          ***
 ***  You are free to distribute this software under the      ***
 ***  terms of the GNU General Public License                 ***
 ***                                                          ***
 ***  A Pretty Advanced 'Hello World!' Program                ***
 ****************************************************************

 Thu Apr  4 09:59:38 2019
  TITLE:

 INFO: Detected TURBOMOLE input

 Number of atoms =  12

 Normalizing basis

   Total number of primitive  GTO's    354
   Total number of contracted GTO's    252

 *** Calculating screening coefficients
 INFO: Screening threshold:   0.1000E-07

 INFO: Reordering densities [TURBOMOLE]

 Integration grid data
 ------------------------------------------------
 center     2.277078   -0.005328    0.000000
 origin     7.277078   -0.005328   -5.000000
 basv1     -0.000000   -0.000000    1.000000
 basv2     -1.000000   -0.000000   -0.000000
 basv3      0.000000   -1.000000    0.000000
 lenghts   10.000000    7.200000    0.000000
 magnet     0.000000    0.000000   -1.000000

 Grid mode = bond
 INFO: Integration grid selected.
 INFO: Adjusted number of grid points for quadrature:    36   36    0
   Number of grid points <v1,v2>:   36   36    1
   Total number of grid points  :      1296

 *** Grid plot in grid.xyz
 INFO: Closed-shell calculation

 Integrating current density
 *****************************************
 Jmod integration skipped.
 *** Integrating current

 ************************************************************
    Induced current (au)    :     0.418821
       Positive contribution:     0.595166  (  16.771417 )
       Negative contribution:    -0.176344  (  -4.969283 )

    Induced current (nA/T)  :    11.802134
       (conversion factor)  :    28.179409
 ************************************************************


 *** Integrating ACID density

 ************************************************************
    ACID (au) sqrt(delta J^2):     0.118838
    ACID (nA/T)              :     3.348788

 ************************************************************


 *** Deallocated grid data
 INFO: Deallocated basis set and atom data

 ----------------------------------------------------------------------
    wall time:     0.62sec (   0.0 h )
         user:     0.56sec (   0.0 h )
          sys:     0.06sec (   0.0 h )
 ----------------------------------------------------------------------
 Thu Apr  4 09:59:39 2019
 Hello World! (tm)

 done.

**Comment by patrashantigopal** [comment]
Can I use the benzene input file for another system, for example in cyclopentadienyl? Or I need to edit the input file?

**Comment by heikef** [comment]
You have to generate first XDENS and MOL files. Then you have to edit the gimic.input file depending on the molecule you are looking at because there you define the bond of interest for the integration procedure. You can not do this at once for all bonds. You have to do it by hand for each bond. There are some bash scripts shared by @mariavd which can help you with setting up the gimic.inp files. 
Please have also a look at the manual.

**Comment by heikef** [comment]
It is great that you are by now able to run the code!

**Comment by patrashantigopal** [comment]
Some questions regarding the input file making:

    bond=[1,2]                                                                                             **ok**
    fixpoint=4                                                                                              **ok**
#   coord1=[0.0, 0.0, 2.145166] # "atom" coordinates                               **how to get the these values?**
#   coord2=[0.0, 0.0, -2.145166]                                                                 **how to get the these values?**
#   fixcoord=[0.0, 0.0, 0.0]                                                                           **it will be same**
    distance=1.32               # place grid 'distance' between atoms            **half of the bond length in au**
    gauss_order=9               # order for gauss quadrature                         **it will be same**
    grid_points=[30, 30, 0]     # increase this later                                      **it will be same**
#   up=4.0                                                                                                  **it will be same**
#   down=4.0                                                                                             **it will be same**
#   in=1.0                                                                                                   **it will be same**                                  
#   out=6.0                                                                                                **it will be same**             
#   rotation=[0.0,0.0,0.0]      # Rotation of (i,j,k) -> (i',j',k') degrees          **it will be same**
#   spacing=[0.02, 0.02, 0.02]     # spacing of points on grid (i,j,k)           **it will be same**
    height=[-5.0, 5.0]                                                                                  **it will be same**
    width=[-2.2, 5.0]                                                                                   **first value is distance from** 
                                                                                   **centroid to midpoint of the bond, last value same**
# ##    radius=1.0                  # round grid: cut off at radius                   **it will be same**

**Comment by patrashantigopal** [comment]
Dear Heikef,

I think I need to edit the following things in input:

1) How to get the coordinates of atom 1 and 2 (here only the z value is different one is +z and other is -z whereas x and y are 0), but I am unable to get this z value.

2) distance is the half of the bond length in atomic unit.

3) width = [first value is the distance from the centroid to the midpoint of the bond, the second value I can keep to 5 or 6]

All other values I can keep as it is. Looking forward to hearing from you.

Best regards,
Shanti

**Comment by heikef** [comment]
1. you can use the atom number instead when you do not know the coordinates, gimic will create a grid.xyz file and a mol.xyz file - there you find the coordinates in Angstrøm. I am assuming here that you play with the benzene example in the examples folder. Otherwise you should know before the coordinates of the molecule you are interested in. 
2. yes
3. width and height define the dimensions of your integration plane. It depends on the problem you are looking at. To get started you can keep it at -2 and 6 but this has to be adapted depending on the problem you are interested in.

**Comment by patrashantigopal** [comment]
Thank you and now I can make it.

**Comment by heikef** [comment]
Excellent! Then I will close this issue.
