### ISSUE TITLE
Dry runs not functioning

### ISSUE THREAD

**Issue by mariavd** [qmcurrents/gimic#23]
Is there a reason why dry runs have been disabled? 

In the initialize subroutine in gimic.f90 the line is commented out:

` 76         !call getkw(input, 'dryrun', settings%dryrun)`

**Comment by bast** [comment]
Try to find id out with `git blame` and then `git show`. I don't know.

**Comment by mariavd** [comment]
This problem will need to be looked into carefully. Heike mentioned that with dry run settings on there are other issues.

**Comment by heikef** [comment]
I just tested dryrun as "gimic --dryrun" and this works for me. If we do not insist that we want to have the dryrun option in the input file we can close this issue. But please also test and double check.

**Comment by mariavd** [comment]
I just tested that with the latest master version compiled with gfortran and run as gimic --dryrun gimic.inp the calculation is executed and I get values for the induced currents, as well as vti, cube and txt files for current density calculations. I will re-compile with ifort and reply when I finish my work on the test scripts.

**Comment by heikef** [comment]
Thank you. Please check only for " gimic --dryrun " it should not be necessary to specify gimic.inp

**Comment by mariavd** [comment]
No difference with " gimic --dryrun ", unfortunately.

**Comment by heikef** [comment]
ok - then we need to have a closer look at keep the issue open

**Comment by heikef** [comment]
I figured out where it needs to be activated - it works now for me. Please check.

**Comment by bast** [comment]
And what have you figured out? :-)

**Comment by heikef** [comment]
I reactivated it properly and tested it for benzene. Then I filled a pull request. It was already available in settings.f90 but had to be added in gimic.in and and gimic.f90.

**Comment by bast** [comment]
Please next time autoclose the issue with your commit - now they are disconnected.

**Comment by heikef** [comment]
Sorry - after the merge I deleted the branch but I saw no autoclose issue option.

**Comment by bast** [comment]
No, I meant this: https://help.github.com/articles/closing-issues-via-commit-messages/
