### ISSUE TITLE
Gaussian2Gimic syntax error

### ISSUE THREAD

**Issue by patrashantigopal** [qmcurrents/gimic#230]
File "/mnt/c/Users/shantigp/projects/gimic-master/tools/g092gimic/Gaussian2gimic.py", line 490
    print "Spin %s, %s"%( "alpha + beta" if nspin == 1 else ["alpha","beta"][ispin]\
                      ^
SyntaxError: invalid syntax

However, previously I have converted one .fchk file to XDEN and MOL file using this script. Meanwhile, I have installed psi4conda in my system. Is that making the problem?

**Comment by heikef** [comment]
Hm, it looks like a python3 complain about a print statement which is working in python2.

**Comment by heikef** [comment]
If you are not able to fix it yourself you can contact the author of that script: vincent.liegeois@unamur.be

**Comment by patrashantigopal** [comment]
Thank you I will conatct the person.

**Comment by heikef** [comment]
Good. Please let us know when the issue is resolved.

**Comment by patrashantigopal** [comment]
Sure.

**Comment by patrashantigopal** [comment]
I did not receive any reply from Vincent. However, I have solved my problem using python 2.7. I have calculated GIMIC for pyrrole. I am attaching the files, I shall be very grateful if you can check whether my calculations and plots are ok or not. I did the integration over the C2-C3 bond and kept N5 as fixed coordinate. Then using paraview and pvsm state files I have plotted jmod, acid and streamline. Please check.
[pyrrole.zip](https://github.com/qmcurrents/gimic/files/3054522/pyrrole.zip)

**Comment by heikef** [comment]
Looks ok. Please try also to do an arrow plot. This is missing. Then you could try to do an LIC streamline plot. After this you can play with the 3D streamline module if you want to. 
Concerning the integration: in the pyrrole case this looks fine. What you should try for eg. multiring molecule is to do a scan procedure. That means a stepwise integration across your molecule. You can use the interactive bash scripts or write your own scripts. There are also some python scripts shared on the github, which you might find useful. 
https://gimic.readthedocs.io/en/latest/scripts.html
https://github.com/qmcurrents/gimic/tree/master/tools/integration-scan
https://github.com/qmcurrents/gimic/tree/master/tools/python-scripts

**Comment by heikef** [comment]
We adapted gimic meanwhile also to python 3, but when you have a working version that you are able to run I would not start reinstalling it. It is more fun to do a current density analysis than struggling with technical stuff....

**Comment by heikef** [comment]
Note, the python scripts work with python 3. They are done the way  I find it convenient but this might not be convenient for other users. The bash scripts are more general and there you are walked step by step through the setup procedure. Therefore I think it is best to recommend them for a new user. @mariavd wrote them. The other link goes to very old bash scripts but you will easily see the structure, which might be helpful either adapting or writing you own scripts.

**Comment by patrashantigopal** [comment]
Dear Heikef,

Thank you for your reply. Tomorrow I will try to make the arrow plot. Next, I will take anthracene and will try to do stepwise integration across the molecule. While reporting in a publication what I should report regarding the current: (a) integration along a bond or (b) for the whole molecule? 

Best regards,
Shanti

**Comment by heikef** [comment]
It depends on the problem you are looking at. Here you find a lot of examples to get inspiration. 
http://wires.wiley.com/WileyCDA/WiresArticle/wisId-WCMS1270.html

**Comment by vliegeois** [comment]
I have fix the issue with Gaussian2Gimic.py
The script is now python 2 and python 3 compatible.
I attach the file here.
Heike, can you upload them on the repository?
Best regards
Vincent

[gaussian2gimic.zip](https://github.com/qmcurrents/gimic/files/3060589/gaussian2gimic.zip)

**Comment by patrashantigopal** [comment]
Dear Heikef,

I have performed current-profile integration for pyrrole. I am attaching the file, inside there is a .tif file of the plot. Please check. If I am correct then I will do the same for a multi-ring system.

Best regards,
Shanti
[current_profile_pyrrole.zip](https://github.com/qmcurrents/gimic/files/3063190/current_profile_pyrrole.zip)

**Comment by bast** [comment]
Thanks Vincent! I will add your changes to the code. Shanti - I think we should open a new issue or maybe we need a mailing list? I feel these are research questions which have not much to do with the original problem of this issue (syntax error).
