### ISSUE TITLE
Error while plotting in Paraview

### ISSUE THREAD

**Issue by patrashantigopal** [qmcurrents/gimic#232]
**1) When I am trying to make 3D_LIC plot in paraview I am getting the following message:**

![jvec_plot](https://user-images.githubusercontent.com/46942514/55883803-a197df00-5baf-11e9-8bc6-1985633bcdc4.png)
![3D_LIC_plot](https://user-images.githubusercontent.com/46942514/55883306-c3dd2d00-5bae-11e9-8523-4a3994d7104a.png)

view\src\ParaViewCore\ServerManager\Core\vtkSMStateVersionController.cxx, line 621
The state file uses the old 'Glyph' filter implementation. The implementation has changed in ParaView 5.6. Consider replacing the Glyph filter with a new Glyph filter. The old implementation is still available as 'Glyph Legacy' and will be used for loading this state file.

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\VTK\IO\XML\vtkXMLReader.cxx, line 270
vtkXMLImageDataReader (00000216AF22F130): Error opening file C:\Users\suzanka\Documents\UbuntuShared\PhD\10annulene\King-crawford\10annulene-Crawford-Fig.3\align\3D\jvec.vti

Warning: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ServerManager\Core\vtkSMProxy.cxx, line 853
vtkSMSourceProxy (00000216AC7D9450): Proxy (filters, GlyphLegacy)  has been deprecated in ParaView 5.6 and will be removed by ParaView 5.7. 
        It has been replaced by 'GlyphWithCustomSource'. Please consider using that instead.
      

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ClientServerCore\Rendering\vtkCompositeRepresentation.cxx, line 357
vtkPVCompositeRepresentation (00000216A8B01F30): No representation was found with Name: Surface LIC

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\VTK\IO\XML\vtkXMLReader.cxx, line 270
vtkXMLImageDataReader (00000216AF22F130): Error opening file C:\Users\suzanka\Documents\UbuntuShared\PhD\10annulene\King-crawford\10annulene-Crawford-Fig.3\align\3D\jvec.vti

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\VTK\Common\ExecutionModel\vtkExecutive.cxx, line 782
vtkPVCompositeDataPipeline (00000216B8DA65A0): Algorithm vtkFileSeriesReader(00000216B8DA64B0) returned failure for request: vtkInformation (00000216B9A6F180)
  Debug: Off
  Modified Time: 1369395
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA
  FORWARD_DIRECTION: 0
  ALGORITHM_AFTER_FORWARD: 1
  FROM_OUTPUT_PORT: 0

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\VTK\Common\ExecutionModel\vtkExecutive.cxx, line 782
vtkCompositeDataPipeline (00000216B99B8110): Algorithm vtkPVGeometryFilter(00000216B9B40580) returned failure for request: vtkInformation (00000216B9A74A90)
  Debug: Off
  Modified Time: 1370393
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FORWARD_DIRECTION: 0
  ALGORITHM_AFTER_FORWARD: 1
  FROM_OUTPUT_PORT: 0

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\VTK\IO\XMLParser\vtkXMLParser.cxx, line 134
vtkCMLParser (00000216C13B9550): Cannot open XML file: C:\Users\suzanka\Documents\UbuntuShared\PhD\10annulene\King-crawford\10annulene-Crawford-Fig.3\align\3D\mol-bohr.cml

Warning: In C:\bbd\ecd3383f\build\superbuild\paraview\src\VTK\Domains\Chemistry\vtkCMLMoleculeReader.cxx, line 112
vtkCMLMoleculeReader (00000216B8B763C0): Cannot parse file C:\Users\suzanka\Documents\UbuntuShared\PhD\10annulene\King-crawford\10annulene-Crawford-Fig.3\align\3D\mol-bohr.cml as CML.

Generic Warning: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ServerManager\Core\vtkSMStateVersionController.cxx, line 621
The state file uses the old 'Glyph' filter implementation. The implementation has changed in ParaView 5.6. Consider replacing the Glyph filter with a new Glyph filter. The old implementation is still available as 'Glyph Legacy' and will be used for loading this state file.

Warning: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ServerManager\Core\vtkSMProxy.cxx, line 853
vtkSMSourceProxy (00000216ADE48E50): Proxy (filters, GlyphLegacy)  has been deprecated in ParaView 5.6 and will be removed by ParaView 5.7. 
        It has been replaced by 'GlyphWithCustomSource'. Please consider using that instead.
      

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ClientServerCore\Rendering\vtkCompositeRepresentation.cxx, line 357
vtkPVCompositeRepresentation (00000216C13743F0): No representation was found with Name: Surface LIC

Generic Warning: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ServerManager\Core\vtkSMStateVersionController.cxx, line 621
The state file uses the old 'Glyph' filter implementation. The implementation has changed in ParaView 5.6. Consider replacing the Glyph filter with a new Glyph filter. The old implementation is still available as 'Glyph Legacy' and will be used for loading this state file.

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\VTK\IO\XML\vtkXMLReader.cxx, line 270
vtkXMLImageDataReader (00000216AD467DD0): Error opening file C:\Users\suzanka\Documents\UbuntuShared\PhD\10annulene\King-crawford\10annulene-Crawford-Fig.3\align\3D\jvec.vti

Warning: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ServerManager\Core\vtkSMProxy.cxx, line 853
vtkSMSourceProxy (00000216ACF8EC10): Proxy (filters, GlyphLegacy)  has been deprecated in ParaView 5.6 and will be removed by ParaView 5.7. 
        It has been replaced by 'GlyphWithCustomSource'. Please consider using that instead.
      

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ClientServerCore\Rendering\vtkCompositeRepresentation.cxx, line 357
vtkPVCompositeRepresentation (00000216C3F2B9C0): No representation was found with Name: Surface LIC

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\VTK\IO\XML\vtkXMLReader.cxx, line 270
vtkXMLImageDataReader (00000216AD467DD0): Error opening file C:\Users\suzanka\Documents\UbuntuShared\PhD\10annulene\King-crawford\10annulene-Crawford-Fig.3\align\3D\jvec.vti

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\VTK\Common\ExecutionModel\vtkExecutive.cxx, line 782
vtkPVCompositeDataPipeline (00000216C2DC8B30): Algorithm vtkFileSeriesReader(00000216C2DC70F0) returned failure for request: vtkInformation (00000216AF022960)
  Debug: Off
  Modified Time: 3193740
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA
  FORWARD_DIRECTION: 0
  ALGORITHM_AFTER_FORWARD: 1
  FROM_OUTPUT_PORT: 0

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\VTK\Common\ExecutionModel\vtkExecutive.cxx, line 782
vtkCompositeDataPipeline (00000216AE845E80): Algorithm vtkPVGeometryFilter(00000216B9B3FC80) returned failure for request: vtkInformation (00000216AF027230)
  Debug: Off
  Modified Time: 3194738
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FORWARD_DIRECTION: 0
  ALGORITHM_AFTER_FORWARD: 1
  FROM_OUTPUT_PORT: 0

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\VTK\IO\XMLParser\vtkXMLParser.cxx, line 134
vtkCMLParser (00000216AD603FB0): Cannot open XML file: C:\Users\suzanka\Documents\UbuntuShared\PhD\10annulene\King-crawford\10annulene-Crawford-Fig.3\align\3D\mol-bohr.cml

Warning: In C:\bbd\ecd3383f\build\superbuild\paraview\src\VTK\Domains\Chemistry\vtkCMLMoleculeReader.cxx, line 112
vtkCMLMoleculeReader (00000216B8B76570): Cannot parse file C:\Users\suzanka\Documents\UbuntuShared\PhD\10annulene\King-crawford\10annulene-Crawford-Fig.3\align\3D\mol-bohr.cml as CML.

Generic Warning: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ServerManager\Core\vtkSMStateVersionController.cxx, line 621
The state file uses the old 'Glyph' filter implementation. The implementation has changed in ParaView 5.6. Consider replacing the Glyph filter with a new Glyph filter. The old implementation is still available as 'Glyph Legacy' and will be used for loading this state file.

Warning: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ServerManager\Core\vtkSMProxy.cxx, line 853
vtkSMSourceProxy (00000216AD226D20): Proxy (filters, GlyphLegacy)  has been deprecated in ParaView 5.6 and will be removed by ParaView 5.7. 
        It has been replaced by 'GlyphWithCustomSource'. Please consider using that instead.
      

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ClientServerCore\Rendering\vtkCompositeRepresentation.cxx, line 357
vtkPVCompositeRepresentation (00000216B9F819C0): No representation was found with Name: Surface LIC

**The picture which I got is attached herewith.**

**2) When I am plotting jvec then also I am getting the following message:**

Generic Warning: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ServerManager\Core\vtkSMStateVersionController.cxx, line 621
The state file uses the old 'Glyph' filter implementation. The implementation has changed in ParaView 5.6. Consider replacing the Glyph filter with a new Glyph filter. The old implementation is still available as 'Glyph Legacy' and will be used for loading this state file.

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\VTK\IO\XML\vtkXMLReader.cxx, line 270
vtkXMLImageDataReader (0000020815F9E210): Error opening file @JVEC@

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ClientServerCore\Rendering\vtkCompositeRepresentation.cxx, line 357
vtkPVCompositeRepresentation (000002081F0FFE50): No representation was found with Name: Surface LIC

Warning: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ServerManager\Core\vtkSMProxy.cxx, line 853
vtkSMSourceProxy (00000208135E8C60): Proxy (filters, GlyphLegacy)  has been deprecated in ParaView 5.6 and will be removed by ParaView 5.7. 
        It has been replaced by 'GlyphWithCustomSource'. Please consider using that instead.
      

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\VTK\IO\XML\vtkXMLReader.cxx, line 270
vtkXMLImageDataReader (0000020815F9E210): Error opening file @JVEC@

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\VTK\Common\ExecutionModel\vtkExecutive.cxx, line 782
vtkPVCompositeDataPipeline (00000208127381A0): Algorithm vtkFileSeriesReader(0000020812739EB0) returned failure for request: vtkInformation (00000208142944E0)
  Debug: Off
  Modified Time: 1225198
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA
  FORWARD_DIRECTION: 0
  ALGORITHM_AFTER_FORWARD: 1
  FROM_OUTPUT_PORT: 0

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\VTK\Common\ExecutionModel\vtkExecutive.cxx, line 782
vtkCompositeDataPipeline (0000020814966B30): Algorithm vtkPVGeometryFilter(00000208146846C0) returned failure for request: vtkInformation (000002081429C960)
  Debug: Off
  Modified Time: 1225240
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  FORWARD_DIRECTION: 0
  ALGORITHM_AFTER_FORWARD: 1
  FROM_OUTPUT_PORT: 0

Generic Warning: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ServerManager\Core\vtkSMStateVersionController.cxx, line 621
The state file uses the old 'Glyph' filter implementation. The implementation has changed in ParaView 5.6. Consider replacing the Glyph filter with a new Glyph filter. The old implementation is still available as 'Glyph Legacy' and will be used for loading this state file.

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ClientServerCore\Rendering\vtkCompositeRepresentation.cxx, line 357
vtkPVCompositeRepresentation (0000020820CF03F0): No representation was found with Name: Surface LIC

Warning: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ServerManager\Core\vtkSMProxy.cxx, line 853
vtkSMSourceProxy (000002082110AE10): Proxy (filters, GlyphLegacy)  has been deprecated in ParaView 5.6 and will be removed by ParaView 5.7. 
        It has been replaced by 'GlyphWithCustomSource'. Please consider using that instead.
      

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ServerImplementation\Core\vtkPVSessionCore.cxx, line 371
vtkPVSessionCore (000002080F6503E0): Object type: vtkSMTimeKeeper, could not find requested method: "RemoveSuppressedTimeSource"
or the method was called with incorrect arguments.

while processing
Message 0 = Invoke
  Argument 0 = vtk_object_pointer {vtkSMTimeKeeper (000002081335EB20)}
  Argument 1 = string_value {RemoveSuppressedTimeSource}
  Argument 2 = vtk_object_pointer {vtkObjectBase (0000020813E316C0)}

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ServerImplementation\Core\vtkPVSessionCore.cxx, line 372
vtkPVSessionCore (000002080F6503E0): Aborting execution for debugging purposes.

ERROR: In C:\bbd\ecd3383f\build\superbuild\paraview\src\ParaViewCore\ServerImplementation\Core\vtkSIProxy.cxx, line 135
vtkSIProxy (0000020812D0FEF0): Error pushing property state: SuppressedTimeSources

**The picture is also attached.**

**Please help.**

**Comment by patrashantigopal** [comment]
Dear Heikef,

I need your email id. I have gone through your homepage but could not find the email id.

Sincerely.
Shanti

**Comment by bast** [comment]
Maybe we should set up a mailing list, otherwise all emails will go to Heike directly and that is perhaps not fair :-)

**Comment by patrashantigopal** [comment]
ok

**Comment by heikef** [comment]
Did you go through the manual and had a look at the youtube links?

**Comment by patrashantigopal** [comment]
Yes, I have watched the videos but I did not go through the manual. But still, I will repeat everything and will report to you.

**Comment by heikef** [comment]
Ok. Thank you as well for the feedback. We probably have to write a tutorial....

**Comment by heikef** [comment]
Since you opened a new issue I will close this one.
