### ISSUE TITLE
how to calculate magnetizability using GIMIC?

### ISSUE THREAD

**Issue by patrashantigopal** [qmcurrents/gimic#243]
How can I calculate magnetizability using GIMIC?

**Comment by heikef** [comment]
This got very recently implemented and has not been published yet. This means it is not tested carefully so to speak in action. I do not recommend using it in it's current state. If you are after the magnetizability you can use other codes eg. like Dalton or Gaussian 09.

**Comment by patrashantigopal** [comment]
ok
