### ISSUE TITLE
Valgrind test is brittle

### ISSUE THREAD

**Issue by bast** [qmcurrents/gimic#245]
We need to make it more robust. We sometimes get failures out of the blue.

**Comment by heikef** [comment]
How can we do this? Maybe we should switch these tests off until the issue is fixed?

**Comment by bast** [comment]
If we switch it off, it will never be fixed :-) I think I know how - will work on it soon.

**Comment by heikef** [comment]
Ok, thank you.

**Comment by bast** [comment]
My attempted solution will be: instead of brittle string comparison matching I will try to check for the Valgrind return code.

**Comment by bast** [comment]
PR coming up - in short, runtest was not the right solution to test for Valgrind errors. I found a shorter/simpler route.

**Comment by heikef** [comment]
Great, thank you!
