### ISSUE TITLE
Implement testing on Travis

### ISSUE THREAD

**Issue by bast** [qmcurrents/gimic#25]
What is the status with tests @mariavd @heikef? Maybe it was described in some email (sorry, too many emails) - if yes, can you please describe here how the testing currently works so that I can hook it up with Travis? I think we need the automated testing before doing anything else.

**Comment by mariavd** [comment]
There are the testing bash scripts in the test directory. They return 0 on success. You can check the README for more details and please let me know if something is unclear.

**Comment by heikef** [comment]
Agreed. Automated testing would be great! Thank you for pushing this forward!
Our tests are in the directory test/benzene and test/C4H4  - last time when I tested things went
through. However, I did not do a recent test (yesterday) but Maria did and things were working. So we can take those two examples to get started with.

**Comment by bast** [comment]
Thanks for the info :-) I will set it up ASAP. Will keep this issue open until then.

**Comment by bast** [comment]
Thanks! Your script seems to work. I will restructure the documentation a bit (move it to top level README) and then also connect it to Travis.

**Comment by bast** [comment]
The automated testing will also help me to remove the heaps of unused cruft that is now sitting in the code. I will move all the MRChem stuff to a separate branch.

**Comment by mariavd** [comment]
Nice to hear. I believe it will be alright for Travis to run the scripts as described in the README - giving the working directory as an argument. In the master branch the 2D and 3D tests are running only for the benzene molecule. I could add the input files for C4H4, as well, if you think it's necessary.

**Comment by bast** [comment]
Let us start with Benzene. No problem to add more later.

**Comment by bast** [comment]
I am about to hook up the automated testing. For me `gimic-test-2D.sh` and `gimic-test-3D.sh` fail. Is this expected? Also it is currently not ideal that the tests modify files which are tracked in the repo. The generated files should either be ignored, or even better: be written to the build directory. It is good if no generated files are written outside the build directory. The reason for this is that we want to be able to build several builds with the same source.

**Comment by mariavd** [comment]
I am trying to fix it as soon as possible. My laptop has been unreliable lately, so there might be some delay. I have some commits and local changes that are not merged, so maybe that's why the scripts don't work as expected. A pull request will come when the issue appears to be solved.

**Comment by bast** [comment]
Thanks! Now the tests pass. We will follow the problem with generated files in the source tree in a separate issue: https://github.com/qmcurrents/gimic/issues/28.

**Comment by bast** [comment]
This is now done.
