### ISSUE TITLE
"make test" should check whether runtest is installed/activated

### ISSUE THREAD

**Issue by bast** [qmcurrents/gimic#255]
Otherwise all tests "fail" and the user may not easily know why which creates confusion and more email traffic for the maintainers/developers.

**Comment by heikef** [comment]
Good idea! I just got a user support request which might be related to this.

**Comment by bast** [comment]
But then again, the tests will then fail quickly with a hopefully clear enough error message and our install instructions are hopefully clear enough and I think we can rather fix this by improving documentation.
