### ISSUE TITLE
How to print jmod.txt

### ISSUE THREAD

**Issue by vbrmk** [qmcurrents/gimic#256]
Sir how to generate jmod.txt files. when I am running gimic.inp it is generating only jmod.vti.

**Comment by heikef** [comment]
The jmod.txt option has been removed. You can use jmod.vti instead. Note, when you run gimic with grid bond and the cdens module the jmod.txt should be created. For all other options it has been removed.

**Comment by vbrmk** [comment]
Thank you sir.
