### ISSUE TITLE
Release, DOI, and citation

### ISSUE THREAD

**Issue by bast** [qmcurrents/gimic#263]
I suggest we soon create a new release and also create a DOI to make the code citeable.

Some contributions, for instance mine, are now "invisible": https://github.com/qmcurrents/gimic#citation

Therefore I would like to get a DOI with all authors/contributors listed.

**Comment by heikef** [comment]
Sure, this is a good idea. Your contributions do not need to be invisible. You can add the github pages for the projects to the citation section for example. This would be a quick solution until we have the doi, which we should get as soon as possible.

**Comment by bast** [comment]
I can take care of the technical side of it.

What we need to decide is:
- Are we ready to make a new release? Any issue that needs to be addressed before we do that?
- Do we want a distinction between authors and contributors? If yes, who are the code authors?

**Comment by heikef** [comment]
I would feel better if #261 would be solved before doing the release. 

In my view the code author is Jonas. The rest of us did only contributions to the code or cleaned it up. Then there are those who did not contribute to the code itself but helped with documentation and shared scripts, which is also important for the whole project.

**Comment by heikef** [comment]
@bast since the two of us wrote an application and got funding to bring gimic in a better shape it would be good if we could also publish our achievements with a doi. It would clearly document our results to our stakeholder.

**Comment by bast** [comment]
DOI is a must. I agree that we fix #261 first. And I agree that Jonas is author and everybody else is contributor.

**Comment by heikef** [comment]
This would be an easy solution and none of us would feel less important. Github documents the contributions of each of us. You clearly stand out. We could give you the title main developer or core developer to stress the importance of your contributions.

**Comment by bast** [comment]
As soon as we fix the other issue, I will send a draft pull request with a suggestion for authorship, then another pull request for a new version, finally a DOI.

**Comment by heikef** [comment]
Has something happend here? Where do we get a doi?

**Comment by bast** [comment]
Zenodo. Self-assigning so that I don't forget. This and next week on vacation but once I am back I will pick it up.

**Comment by heikef** [comment]
I know you will not like this comment but we have the year 2023 by now and nothing happened. Let`s talk bilateral and get this issue going. It is important and relevant. @bast

**Comment by bast** [comment]
There is no problem at all reminding me. I appreciate. And you can help me to get this off the road by creating a [CITATION.cff](https://citation-file-format.github.io/) file. I can then do all the rest.

**Comment by heikef** [comment]
In the current stage of the code it fails when running the testsuite on github. This has to be fixed before setting up a release and publishing something. I can take care of the citation.cff file but we need to decide on how to get organized.

**Comment by bast** [comment]
I will look at the memory leak and you can draft a CITATION.cff file and hopefully we can then complete both at the same time and release and get a DOI.

**Comment by heikef** [comment]
Ok, I will see to get this done.

**Comment by heikef** [comment]
@bast I committed a first draft of a [cff file.](https://github.com/qmcurrents/gimic/blob/master/CITATION.cff) Please check. I wonder if it is possible to integrate all related references we have. Plus we do not have emails and orcids for all people listed. I included everybody I remember, which might be incomplete.

**Comment by bast** [comment]
I am looking at it finally ...

**Comment by bast** [comment]
The test problem is followed up in #300.

**Comment by bast** [comment]
I confirm now that the CITATION.cff and .zenodo.json parts are done and in my opinion we are ready for a release.

**Comment by heikef** [comment]
Then let`s go for it. We can update the cff and zenodo information if needed be. Perhaps we should also email everybody and inform them?

**Comment by bast** [comment]
OK I will create a release and deposit to Zenodo this week.

**Comment by heikef** [comment]
Thank you! I think it is more important to make the code citable than making it perfect. Just tested your recent changes on my local machine and it works!

**Comment by bast** [comment]
I fully agree. We can always adjust later but getting a DOI is the priority. It will be very little work and I will do that very soon.

**Comment by bast** [comment]
My understanding is that GIMIC will be released now with version 2.0.0. [Here](https://github.com/qmcurrents/gimic/blob/master/cmake/custom/version.cmake) I see 2.1.4. Until now, do people refer to a specific version when they cite GIMIC?

**Comment by bast** [comment]
Also output says:
```
 ****************************************************************
 ***                                                          ***
 ***           GIMIC 2.1.4 (27a3071)                              ***
 ***              Written by Jonas Juselius                   ***
 ***                                                          ***
 ***  This software is copyright (c) 2003-2011 by             ***
 ***  Jonas Juselius,  University of Tromso.                  ***
 ***                                                          ***
 ***  You are free to distribute this software under the      ***
 ***  terms of the GNU General Public License                 ***
 ***                                                          ***
 ***  A Pretty Advanced 'Hello World!' Program                ***
 ****************************************************************
```

**Comment by bast** [comment]
So maybe the new version should be `v2.2.0`?

**Comment by bast** [comment]
Release v2.2.0 is out, DOI is set and recommended citation added to README.md.
