### ISSUE TITLE
Document minimum supported compiler versions

### ISSUE THREAD

**Issue by bast** [qmcurrents/gimic#264]
The code does not build with GNU Fortran 4.4.7 and for me that's not a problem but we should document the minimum version required to build the code.

**Comment by heikef** [comment]
Ok, maybe the installation section is a good place for this.

**Comment by lnw** [comment]
+ python versions

**Comment by heikef** [comment]
Did something happen in this direction?

**Comment by heikef** [comment]
This seems to be outdated. Closing the issue. We can reopen it when needed be.
