### ISSUE TITLE
sign issue of the current strength

### ISSUE THREAD

**Issue by patrashantigopal** [qmcurrents/gimic#267]
I am trying to calculate the current strength of some aromatic metal chelate rings. According to NICS values (negative value), these are aromatic but while calculating current strength using GIMIC it is giving negative current value instead of a positive one. I shall be very helpful if someone can guide me to solve this issue.

**Comment by bast** [comment]
Is the question about the sign convention of the GIMIC code? If yes, I recommend to take a "simple"/known molecule such as benzene and we can double-check.

Or is the question about why for a certain compound one approach yields a different result than another approach? This can be difficult to answer. Also for this it would be good to look at an explicit example.

**Comment by patrashantigopal** [comment]
I have checked benzene and other standard molecules which are giving expected result. So my question is "why for a certain compound one approach yields a different result than another approach?". Since I would like to publish my results I want to make sure that I am not making any fundamental mistake. Can please tell me such example where NICS and GIMIC give opposite results?

**Comment by heikef** [comment]
This is hard to tell when not knowing what molecule you are looking at. In general you should start the integration in the center of the ring and go to the outside. A good check is doing a stepwise integration and generating a current strength profile. Then typically paratropic currents circle on the inside of the ring and diatropic ones on the outside. I suggest to practise this first with benzene and then go to your other molecule. You can do this by either writing your own script or using the bash scripts from the folder jobscripts. Hope this helps.

**Comment by patrashantigopal** [comment]
please check the integration profile. I am getting positive current inside the ring and negative outside the ring.

![integration profile](https://user-images.githubusercontent.com/46942514/64530324-81fb1300-d315-11e9-8f92-252b889ad60d.jpg)

**Comment by heikef** [comment]
You need to reverse the sign here. Outside should be the diatropic currents.

**Comment by patrashantigopal** [comment]
Alright and the net current would be negative as I obtained in the integration. Then the molecule is anti-aromatic?

**Comment by heikef** [comment]
In principle yes. It depends on the net ring current strength  you get. If the value is small and negative one can interpret it also as weakly anti-aromatic to nonaromatic. For example -0.5 - 2 nA/T is most likely nonaromatic -3-5 weakly ant-aromatic and -12 - 24 nA/T anti-aromatic. But this is not set in stone it depends on the molecule you are looking at. It makes sense to use benzene and c4h4 as reference systems for example. In case of doubt report the value you obtain and tell on what you base your assessment and normally this should be fine.

**Comment by heikef** [comment]
When the bond lies to the right then the fixpoint should be on the left (eg. center of the ring). In case of doubt I would always do a scan over the bond of interest as you did now which lead to the current strength profile you shared.

**Comment by heikef** [comment]
Please let us know if this was of use for you. If yes we can close the issue. Thank you.

**Comment by patrashantigopal** [comment]
Thank you very much for your elaborate explanation. Now you can close the issue.

**Comment by heikef** [comment]
You are welcome.
