### ISSUE TITLE
Relativistic calculations

### ISSUE THREAD

**Issue by patrashantigopal** [qmcurrents/gimic#268]
Is it possible to perform GIMIC calculations using relativistic approximation?

**Comment by bast** [comment]
You mean a 4-component relativistic calculation? Or what level of approximation do you have in mind?

**Comment by patrashantigopal** [comment]
ZORA calculations.

**Comment by heikef** [comment]
No, ZORA is not possible, but it is possible to include ECPs in the calculation. This normally leads to good results, because mainly valence electrons are involved in the ring current.
