### ISSUE TITLE
cmake3/python3

### ISSUE THREAD

**Issue by lnw** [qmcurrents/gimic#274]
@bast @heikef @mariavd 
 I have written a patch, mostly for myself, that bumps the cmake version to 3.12+, python to strictly 3.0+, and uses the newer (since 3.12) method of cmake to find python including numpy.

-- should that be merged?  I'm not offended if not, I think it makes sense and is properly done, but I can't tests in many other settings.
-- what was the reason for shipping FIndPython/FindNumpy cmake files (which are old + unmaintained).  Was there ever a problem when not doing that? (I'm asking because I'm deleting some of those.)

**Comment by heikef** [comment]
@lnw to me it sounds reasonable, did you run the testsuite?

**Comment by lnw** [comment]
I did not run the tests, just a single example.  Running the tests would be besides the point, because I didn't change the code, just the build system.  So, if anything compiles, links, and finds libraries, nothing can go wrong.

**Comment by heikef** [comment]
@lnw Please share what you have then @bast can do a code review. If you want to do a git pull. There is some new stuff you can play around with if you find time for it.

**Comment by bast** [comment]
I think this sounds like a good idea. I think the motivation to ship those now outdated files was that the support for finding Python was less good back then.

**Comment by heikef** [comment]
Closing the issue since it has been resolved. See: https://github.com/qmcurrents/gimic/pull/278
