### ISSUE TITLE
Testing generates files into the source tree

### ISSUE THREAD

**Issue by bast** [qmcurrents/gimic#28]
All generated files should ideally be written to the build directory.

**Comment by mariavd** [comment]
I see your point but Gimic writes the vti, txt and cube files in its working directory. At the moment the only solution that comes to my mind is to copy these files to the build directory after the calculation ends.

Yesterday's pull request should have deleted the existing vti, txt and cube files, so they are no longer overwritten during testing. I don't know if this can be considered a solution, though.

**Comment by bast** [comment]
Then we need to change Gimic to be able to write output files to a directory that can be set by the user. Please run the tests in a clean Git repo and then run `git status` and you will see all files which are modified.

**Comment by mariavd** [comment]
Bond integration:
	grid.xyz
	mol.xyz

2D:
	grid.xyz
        mol.xyz
	acid.txt
	jmod.txt
	jvec.txt
	jvec.vti

3D:
	grid.xyz
	mol.xyz
	acid.cube
	acid.txt
	acid.vti
	jmod.cube
	jmod.txt
	jmod.vti
	jmod_quasi.cube
	jvec.txt
	jvec.vti

**Comment by heikef** [comment]
Alternatively one could create in the build directory another directory named test and run the tests there. Is this possible with cmake? This might be a good alternative to keep things simple.

**Comment by bast** [comment]
Disadvantage of copying test files is that they become disconnected from the Git repo. If you modify them, you risk forgetting to commit the changes. If you reconfigure, you risk overwriting your changes. It cannot be very difficult to write generated files to a directory that is set by the user.

**Comment by heikef** [comment]
I understand. We do not want to be disconnected from Git repo.

**Comment by mariavd** [comment]
How about the test script creating a directory tmp, where it copies the gimic.inp file, and does the calculations there? The reference files can still be in the test directory. Before exiting the script would delete the tmp directory.

**Comment by bast** [comment]
Sounds good. It may be OK to not delete the tmp directory if you want to figure out what went wrong.

**Comment by heikef** [comment]
There is already a PyGimicTest.py.in file available - we should check this - probably it can easily be extended.

**Comment by bast** [comment]
Yes. When you run "make test" then some stuff is run which fails. No idea what that is. We need to do archaeology.

**Comment by heikef** [comment]
This is probably related to the idea to rewrite gimic in python.

**Comment by heikef** [comment]
In gimic/build/test are several python files for testing - the "make test" command executes the PyGimicTest.py there but there is also a test.py and input files.

**Comment by mariavd** [comment]
It would be nice that the people involved in Gimic decide how it should grow. If some prefer rewriting it in Python, then I don't see how I can be of any use. Dage was suggesting that I write some CUDA or OpenACC code but that would be useless if the next student starts over in a different language. 

If "make test" is working, then this Python script could also call the bash scripts, so that everything is done with one command. Or maybe I should see how to rewrite the bash scripts in Python but that will take a while because I'm not well familiar with it.

**Comment by heikef** [comment]
I investigated. There are a set of errors in the input files bondint.inp and vectors.inp. Then there is a name missmatch in test.py. I know what to modify and can add it. Then test.py would work and could be used / adapted further for test purpose. Concerning PyGimicTest.py this seems to be meant for the pygimic part. However, pygimic is not finished and working and I do not know if this will be developed further. We can keep it for the moment and see that some automatic testing is working.

**Comment by heikef** [comment]
I agree that only one command "make test" would be very convenient. In gimic/test the *.in files need to be modified. Then within cmake in gimic/build/test the input files for the different test and the test.py is created. This is then executed und "make test". For the moment make test will run PyGimicTest.py but this can be changed to test.py and within test.py we could create subdirectories and or simply use gimic-test.sh. So we are still under git repo but have all test related stuff in build.

**Comment by mariavd** [comment]
What is your suggestion about the *.in files? I could change them before making the pull request.

**Comment by heikef** [comment]
there are a set of "little things" I can send you the working inp files and you edit the *.in.py files - would that be ok?

**Comment by mariavd** [comment]
Oh, sorry, I thought you were talking about the *.pvsm.in files. You can send me those *.in.py files but I might not be able to fix them right away.

**Comment by heikef** [comment]
Then it is probably easier/faster if I file my own pull request.

**Comment by mariavd** [comment]
Yes, sure.

**Comment by bast** [comment]
No problem to bundle everything under "make test".

**Comment by heikef** [comment]
prepared test.py such that it works under "make test" - and filed a pull request - then Maria has a structure to include the tests we already have - please have a look and check/comment

**Comment by bast** [comment]
If you reference a PR (or an issue), please really reference it. Otherwise it is not clear which PR or issue you mean (now it is clear since there are not many).

**Comment by heikef** [comment]
Thanks for pointing this out! 
PR:  #30

**Comment by bast** [comment]
Always think about the future PhD student who 5 years from now will try to figure out what and why we were doing in this issue :-)

**Comment by heikef** [comment]
Can we close this issue after the latest changes? We have by now automatic testing.

**Comment by bast** [comment]
No because testing still generates files in the source tree. I will self-assign.
