### ISSUE TITLE
can not compile gimic any more after moving to python3 

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#280]
I installed the latest Anaconda 3 version and all requested packages. First it had problems to find cmake, then python, then cython and later on numpy. This should not be like this. I found partly a work around by defining cmake option in the setup script: 

./setup --cmake-options="-DCYTHON_EXECUTABLE=/Users/heike/opt/anaconda3/bin/cython -DPYTHON_LIBRARIES=/Users/heike/opt/anaconda3/lib/libpython3.8.dylib:/Users/heike/opt/anaconda3/include/python3.8"

then the setup script did not print out any complains any more but

cd build ; make 
ended up like this: 

[ 57%] Linking CXX static library libgimic2.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libgimic2.a(kinds.f90.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libgimic2.a(kinds.f90.o) has no symbols
[ 57%] Built target gimic2
src/libgimic/CMakeFiles/gengauss.dir/build.make:104: *** target pattern contains no `%'.  Stop.
make[1]: *** [src/libgimic/CMakeFiles/gengauss.dir/all] Error 2
make: *** [all] Error 2

@lnw do you have an idea on how to solve this?

**Comment by bast** [comment]
I am also testing this now on my side ...

**Comment by bast** [comment]
Also on my side it cannot find Cython. Once I rename [here](https://github.com/qmcurrents/gimic/blob/d4a9a638913e6d8923e1bfd83902aecf49e1b062/cmake/custom/FindCython.cmake#L25) "cython3" to "cython", this works.

Then I get complaints about "fatal error: numpy/arrayobject.h: No such file or directory".

**Comment by bast** [comment]
Looking into the "numpy" problem ...

**Comment by heikef** [comment]
Thanks! I am also back at the "numpy" problem. This seems again related to cython. I found this page https://stackoverflow.com/questions/14657375/cython-fatal-error-numpy-arrayobject-h-no-such-file-or-directory

**Comment by lnw** [comment]
If you can find cython but not cython3, are you sure you have the python3-version of cython installed?  On my fairly modern debian setup, there exists only cython3, not cython, and on the four-year-old ubuntu travis system there is also a cython3 available ...

**Comment by heikef** [comment]
@lnw on the mac you install anaconda3 and then cython3 is called cython

**Comment by bast** [comment]
> If you can find cython but not cython3, are you sure you have the python3-version of cython installed? On my fairly modern debian setup, there exists only cython3, not cython, and on the four-year-old ubuntu travis system there is also a cython3 available ...

I install Cython via requirements.txt/venv. And in this case it takes the latest one and in my case it is "cython", not "cython3". We can also adapt CMake code to look for "cython3" and if none found, look for "cython". And only then to fail.

**Comment by lnw** [comment]
Yes, I hadn't edited the requirements.  A switch in cmake might be a good option if we have to search for both.

**Comment by heikef** [comment]
We still do not understand why the numpy problem pops up.

**Comment by bast** [comment]
The numpy problem I have seen earlier. Numpy is installed and the header file exists but CMake is not informed about its location.

**Comment by heikef** [comment]
Is there a trick to solve this?

**Comment by bast** [comment]
Working on it ...

**Comment by heikef** [comment]
Thanks a lot!

**Comment by bast** [comment]
I have a fix now also for the numpy issue. PR incoming ...

**Comment by heikef** [comment]
Cool! Perhaps @lnw wants to have a look as well.

**Comment by heikef** [comment]
Why went everything through when @lnw filed his pull request and later on we had so much trouble?

**Comment by bast** [comment]
Because you and me install GIMIC differently than lnw and than the automated testing. We may want to extend the automated testing.

**Comment by bast** [comment]
To be very clear, lnw did everything right. These things often pop up once tested by others. This is because there are so many ways to install Python dependencies.

**Comment by heikef** [comment]
I thought as well that lnw did everything right, otherwise I would not have merged. He put a lot of time into this.

**Comment by bast** [comment]
So I understand this still fails for you Heike?

**Comment by heikef** [comment]
Yes, it still failes. 
It gives still error messages and refuses to compile. 

Undefined symbols for architecture x86_64:
  "_PyBaseObject_Type", referenced from:
      ___pyx_pw_8gengauss_1gausspoints in gengauss.c.o
  "_PyBuffer_Release", referenced from:
      ___Pyx__GetBufferAndValidate.constprop.13 in gengauss.c.o
      ___pyx_pw_8gengauss_1gausspoints in gengauss.c.o

      ___Pyx_AddTraceback in gengauss.c.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [src/libgimic/gengauss.so] Error 1
make[1]: *** [src/libgimic/CMakeFiles/gengauss.dir/all] Error 2
make: *** [all] Error 2

Ideas?

**Comment by bast** [comment]
But it's a different error now, right?

**Comment by heikef** [comment]
Yes, this is also my impression. Got only a warning regarding numpy. 
/Users/heike/opt/anaconda3/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
[ 64%] Linking CXX shared module gengauss.so
Undefined symbols for architecture x86_64:


Every python error is related to gengauss.c.o

**Comment by lnw** [comment]
everything still works here :)  I assume Python3_INCLUDE_DIRS and the respective numpy place are the same for me.

**Comment by lnw** [comment]
What you are seeing is definitely a linking problem.  In the above ./setup line that you're mentioning, you write PYTHON_LIBRARIES.  Should that be Python3_LIBRARIES?  (It should of course find those by itself ...)

**Comment by heikef** [comment]
@lnw thanks but this does not work either

**Comment by lnw** [comment]
you could try the last commit in https://github.com/lnw/gimic/tree/remove-cmake2python2 . If that doesn't work, I'd be interested to see the output of compiling after setting the main CMakeFile to verbose (CMAKE_VERBOSE_MAKEFILE -> true)

**Comment by heikef** [comment]
On a ubuntu shell it works after installing anaconda3. On the mac it still does not work even after removing and reinstalling anaconda3.

**Comment by lnw** [comment]
What error messages do you get with the above patch?  What does the verbose cmakefile say?

**Comment by heikef** [comment]
I am closing this issue. There is no solution for me and the Mac.

**Comment by lnw** [comment]
@heikef Ok, let's fix this some other time.  I'm sure there are not many lines to left to repair.
