### ISSUE TITLE
Generation of Gaussian cube files

### ISSUE THREAD

**Issue by felixplasser** [qmcurrents/gimic#284]
Hi, I was wondering if there is a way to generate Gaussian cube files of the current densities with GIMIC. This would allow me to use VMD for plotting.

It seems like cube files are present in the [example folder](https://github.com/qmcurrents/gimic/tree/master/examples/benzene/3D). But don't understand how to produce them.

Thanks!
Felix

**Comment by felixplasser** [comment]
Let me just add a quick note on this: I was able to generate a cube file from the vti file. The data seems compatible. I just had to generate the header myself. And I had to switch the x and z axes because the data is ordered in a different way. I think I'll write a conversion tool.

**Comment by heikef** [comment]
Hi Felix, we do not support cube files any more since one can do better visualizations of the current density using ParaView, which we recommend.

**Comment by heikef** [comment]
Depending on what one wants to do it should not be too difficult to reactivate the print out routine for cube files. However, it seems you solved the problem yourself.

**Comment by felixplasser** [comment]
ok, thanks for getting back! It's just that I have some scripts for processing cube files and visualising them with VMD and pymol. So, it would be nice to have the option, especially for ACID plots.

I played around a bit and it seems like I can create proper cube files if I adapt the code from `vtkplot.f90`. So, if there is no official support for cube files in GIMIC, then I would just upload the code into my fork on github in case anyone needs it.

**Comment by bast** [comment]
Thanks Felix! I think it would be nice if we can share the solution and personally I find the cube files useful. Even if other formats are more powerful, cube files are "standard".

**Comment by felixplasser** [comment]
ok, sounds good! This is what I have so far
https://github.com/felixplasser/gimic/blob/master/src/fgimic/vtkplot.f90#L90
My routine `write_cube_imagedata` is just a simple adaptation from the existing `write_vtk_imagedata`

If the functionality should go into the main code, then one would have to consider the following points:

- Where to put it - in a new file?
- When to call it - for every scalar field?
- At the moment it does not recognise any non-standard coordinate system
- At the moment it does not put the molecular geometry in the cube file (but just a dummy H-atom)

I am happy to work on these things if you guide me a bit.

---

Just to give you a bit of a preview. This is what the signed modulus of the current density and ACID plot look like in VMD
![curr10](https://user-images.githubusercontent.com/15384858/104234801-e408e280-544b-11eb-8cbf-32e288b87f76.png)
![ACIDm](https://user-images.githubusercontent.com/15384858/104235421-dc960900-544c-11eb-8f3d-24d22f0421e0.png)

**Comment by bast** [comment]
Thanks Felix! I will soon come back with more info.

**Comment by bast** [comment]
I am sorry this has stalled. Putting this back on my todo list to give you pointers.

**Comment by heikef** [comment]
Closing this issue.... we can reopen it when needed be.
