### ISSUE TITLE
Fortran runtime error: End of file_

### ISSUE THREAD

**Issue by Vivekvdev** [qmcurrents/gimic#288]
While running gimic calculation, I am facing the following error. Kindly help me in resolving the issue.
  __TITLE:

 Number of atoms =  12

 Normalizing basis

   Total number of primitive  GTO's    354
   Total number of contracted GTO's    252

 *** Calculating screening coefficients
 INFO: Screening threshold:   0.1000E-07

At line 133 of file /home/.../gimic/src/libgimic/dens.f90 (unit = 43, file = 'XDENS')
Fortran runtime error: End of file__

**Comment by bast** [comment]
Sorry for replying so late. Is the problem still there? Based on the error message I am guessing that XDENS file did not exist or was in the wrong folder. Can you confirm this?

**Comment by Vivekvdev** [comment]
Haii,
Thank you for your reply.
Ya, the problem was solved. The xdens file was in a different folder.
Thank you,
Vivek

**Comment by bast** [comment]
Great. Glad it worked out. I am now better watching incoming issues so hopefully I will react sooner in future.
