### ISSUE TITLE
Compilation error: src/libgimic/CMakeFiles/gimic2.dir/gausspoints.c.o] Error 1

### ISSUE THREAD

**Issue by dishu1** [qmcurrents/gimic#294]
I'm trying to compile gimic on an Armbian arm64 machine. All the dependencies are surely in place, but the GNU compiler fails to compile jtensor.f90. I switched to the ARM compilers and am getting this:

`Scanning dependencies of target gimic2
[  2%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/kinds.f90.o
[  4%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/settings.f90.o
[  7%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/teletype.f90.o
[  9%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/globals.f90.o
[ 11%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/tensor.f90.o
[ 14%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/acid.f90.o
[ 16%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/gtodefs.f90.o
[ 19%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/intgrl.f90.o
[ 21%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/basis.f90.o
[ 23%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/factorial.f90.o
[ 26%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/cao2sao.f90.o
[ 28%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/caos.f90.o
[ 30%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/bfeval.f90.o
[ 33%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/reorder.f90.o
[ 35%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/dens.f90.o
[ 38%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/gaussint.f90.o
[ 40%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/gausspoints.f90.o
[ 42%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/jtensor.F90.o
[ 45%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/timer.f90.o
[ 47%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/gimic_interface.f90.o
[ 50%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/lip.f90.o
[ 52%] Building C object src/libgimic/CMakeFiles/gimic2.dir/gausspoints.c.o
In file included from /****/*****/********/gimic/src/libgimic/gausspoints.c:2:
/****/*****/********/gimic/src/libgimic/gausspoints.h:4:10: fatal error: 'config.h' file not found
#include "config.h"

         ^~~~~~~~~~
1 error generated.
make[2]: *** [src/libgimic/CMakeFiles/gimic2.dir/build.make:303: src/libgimic/CMakeFiles/gimic2.dir/gausspoints.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:189: src/libgimic/CMakeFiles/gimic2.dir/all] Error 2
make: *** [Makefile:146: all] Error 2`

[CMakeCache.txt](https://github.com/qmcurrents/gimic/files/10418965/CMakeCache.txt)

Note: I was able to compile it on a regular Ubuntu machine but right now I don't wanna do it because I don't wanna use a virtual machine as it takes a lot of disk space.

**Comment by mariavd** [comment]
I'm not well familiar with compilation on ARM chips but it is not a system that we officially support. Are you trying to compile gimic on a Raspberry pi? 

Is your main computer running Windows? You could use WSL there, it's better integrated with the OS kernel than a traditional VM, and it doesn't need tens of gigabytes of disk space just to exist.

**Comment by dishu1** [comment]
No, I'm using RK3588 system. I did manage to compile gimic with ARM compilers and ARM Performance Library, the problem was with anaconda that was preventing cmake from working properly. 
OpenMP isn't working though, gimic runs single-threaded regardless of OMP_NUM_THREADS variable.

**Comment by mariavd** [comment]
Out of curiosity, what was the problem with Anaconda?

Did you remember to use the --omp flag when you compiled?

```
mkdir build && cd build
../setup --omp
```

**Comment by dishu1** [comment]
1) cmake was trying to use anaconda's libraries, such as libcurl, but wasn't able to because of version mismatch.
2) cmake wasn't detecting python and its libraries.
I built gimic using cmake, not using ./setup as it wasn't working properly for me.

**Comment by mariavd** [comment]
I see. Maybe @bast can hint about the issue with the setup?

**Comment by dishu1** [comment]
Cmake configuration allows to set openmp = true so I assumed it was supposed to work the same.

**Comment by mariavd** [comment]
The --omp parameter to the setup script specifies the variable for cmake: -DENABLE_OPENMP=1. You could try that maybe?

**Comment by dishu1** [comment]
It seems to be the same variable as the one cmake sets. I'll try soon.

**Comment by bast** [comment]
Sorry I only found this today under a pile of emails. I will look into the code and soon report back with some hints on how to solve it.

**Comment by bast** [comment]
> "not using ./setup as it wasn't working properly for me"

what failed there?

**Comment by heikef** [comment]
Has this been resolved? There is no new comment since February. I will close this issue. We can reopen it if needed be.
