### ISSUE TITLE
Cmake - gimic build problem

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#298]
There seems to be a cmake problem when trying to build gimic here on github. See pull request #297 

Could NOT find Python3 (missing: Python3_NumPy_INCLUDE_DIRS NumPy) (found version "3.10.6")

@bast you are the one in the team knowing best about cmake, hope it is ok for you to be assigned to this issue. If not please tell and change the assignment.

**Comment by bast** [comment]
I have fixed this in #297.

**Comment by heikef** [comment]
Thank you! Then we close the issue I would say.
