### ISSUE TITLE
Error when I try to use gimic

### ISSUE THREAD

**Issue by kimariyb** [qmcurrents/gimic#299]
Traceback (most recent call last):
  File "/home/kimariyb/gimic/build/bin/gimic", line 21, in <module>
    from fgimic import getkw
  File "/home/kimariyb/gimic/build/lib/python/site-packages/gimic/fgimic/getkw.py", line 20, in <module>
    from pyparsing import \
ImportError: cannot import name 'commaSeparatedList' from 'pyparsing' (/root/.conda/envs/myconda/lib/python3.11/site-packages/pyparsing/__init__.py)

**Comment by bast** [comment]
This error looks like the code uses a functionality which has been deprecated and removed from pyparsing. A workaround could be to use a less new version of Python (e.g. through a conda environment).

**Comment by heikef** [comment]
Is this fixed? If yes I suggest to close that issue. We can reopen it if needed be.

**Comment by chemboyhimanshu** [comment]
Facing the error when i run gimic --dryrun
The error is as 
Traceback (most recent call last):
  File "/home/hsharma/Downloads/GIMIC/build/bin/gimic", line 21, in <module>
    from fgimic import getkw
ModuleNotFoundError: No module named 'fgimic'

**Comment by cmueli** [comment]
> This error looks like the code uses a functionality which has been deprecated and removed from pyparsing. A workaround could be to use a less new version of Python (e.g. through a conda environment).

Has the gimic code been updated to work with the lasted version of all python modules? I just downloaded gimic 2.2.1 and requirements are still the same (pyparsing == 2.4.7)
