### ISSUE TITLE
[Feature] link numgrid library to gimic

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#33]
Therefore we need to modify the cmake stuff. Numgrid is an external library generating DFT grid files. https://github.com/dftlibs/numgrid

**Comment by bast** [comment]
Yup, this is on my table to do that.

**Comment by bast** [comment]
Numgrid is now reasonably converged and can be used. It has C, Fortran, and Python interfaces. I would however not bake it in at the Fortran level. What I would do is to hook it up at the Python level. Much easier and cleaner.

**Comment by heikef** [comment]
Ok, then python.

**Comment by heikef** [comment]
Note, for the visualizations we are currently using an evenly spaced grid is assumed. We might get problems after integrating numgrid as it is. However, these issues can be fixed later. In some cases we will probably not need visualization at all but only integration.

**Comment by heikef** [comment]
You mean external grid calculation - save it on file - read in this file into gimic?

**Comment by heikef** [comment]
It would make sense to download the library via the setup script but where should we add it and how can we link it?

**Comment by heikef** [comment]
A simple solution looks to me to add git+https://github.com/dftlibs/numgrid@master into our requirement.txt file

**Comment by bast** [comment]
Yes, it should go into requirements.txt. Very soon numgrid will become available on PyPI and then it will be sufficient to list "numgrid".

**Comment by heikef** [comment]
List it where? I added it into requirement.txt - something got installed but now I wonder on how to use it. Just import numgrid in a python file?

**Comment by bast** [comment]
Here is a real-life example: https://github.com/dftlibs/numgrid#python-example

**Comment by heikef** [comment]
I saw that example. Thank you. This means one needs to write an extra python program to generate the grid? But all information needed are inside the gimic program and this is written in Fortran. Would it not make more sense to interface numgrid in Fortran such that it can be used inside a Fortran code?

**Comment by heikef** [comment]
Or do you mean make a python program that reads in the MOL file? Then we have coordinate information plus basis set information and can probably extract somehow the alpha min/max stuff needed as input to call numgrid. Afterwards one could write out the grid on a file and read this in as external grid information. What do you think?

**Comment by bast** [comment]
Short term this might be a good way forward. Long term we want to do everything in Python except the low-level computation of the densities.

**Comment by heikef** [comment]
So you suggest not to proceed at the moment?

**Comment by bast** [comment]
It depends on the urgency. If you need this functionality now, proceed. If not, better wait.

**Comment by heikef** [comment]
It is probably hard to estimate on how long one would need to wait. Thanks for sharing your opinion.

**Comment by heikef** [comment]
Perhaps we should consider to work on a dirty hack?

**Comment by bast** [comment]
The Numgrid is "ready" :-) I don't think we need hacks.

**Comment by heikef** [comment]
REALLY?

**Comment by bast** [comment]
I mean the library is ready. It is not part of GIMIC yet. I think interfacing at Fortran level is not a good idea. I would interface at the Python level. But interfacing at Fortran level is possible.

**Comment by heikef** [comment]
I need more information on how to do this at the python level..... maybe an integration on the Fortran level would be more suitable for gimic?

**Comment by bast** [comment]
You can either generate the grid on the Python side and read the grid on the Fortran side or generate the grid directly on the Fortran side. Both is possible, the former is simpler from the linking point of view.

**Comment by heikef** [comment]
That is what I would call a dirty hack. 
1. Generate via python the grid 
2. Save it in a grid.xyz file
3. then run gimic and read the grid in

**Comment by bast** [comment]
OK - for me this would be the simpler way since in the long term, everything will be driven on the Python side. But it is no problem to call the library directly out of Fortran.

**Comment by heikef** [comment]
All right. I understand. So it would be better to keep it in python, because later on the integration into python gimic would be easier.

**Comment by bast** [comment]
Whatever is simpler now is good. It is easy to change. Let's go for whatever is more useful now.

**Comment by heikef** [comment]
I think we have to go for a solution and try. During the process we will quickly figure out what is more useful....

**Comment by heikef** [comment]
I have problems calling numgrid functions. Maybe this is a python issue but I am stuck and need some comments. @bast @lnw 

python mk_grid.py
n 0
proton_charges[n] 6.0
alpha_max[n] 13575.3496820000
max_l_quantum_numbers[n] 3
alpha_min[n] ['0.0951644400', '0.1005682367', '0.3180000000', '0.7610000000']
Traceback (most recent call last):
  File "mk_grid.py", line 116, in <module>
    alpha_min[n] )
TypeError: an integer is required

you find my source here: 
https://github.com/heikef/gimic/blob/feature-numgrid/tools/NumGrid/mk_grid.py

I would be very happy to receive some comments.

**Comment by lnw** [comment]
You are appending a list to a list rather than elements to a list.  If you change the 'append' in line 88 to 'extend' it ought to do what you expect.

**Comment by heikef** [comment]
I was following the example here: https://github.com/dftlibs/numgrid
 ok - I will test if it works by changing line 88 and let you know

**Comment by heikef** [comment]
@lnw the error remains
python mk_grid.py
n 0
proton_charges[n] 6.0
alpha_max[n] 13575.3496820000
max_l_quantum_numbers[n] 3
alpha_min[n] 0.0951644400
Traceback (most recent call last):
  File "mk_grid.py", line 117, in <module>
    alpha_min[n] )
TypeError: an integer is required

extend is not a good idea - I need to give a list not only one element

**Comment by lnw** [comment]
OK, yes I see.  I was just looking at what seems weird.

Let me guess again: change line 52 to 'proton_charges.append(int(l[0]))', because currently the proton charge is a float.

**Comment by heikef** [comment]
I think it is ok to have a float as a proton charge but I will try and let you know.

**Comment by heikef** [comment]
python mk_grid.py
Traceback (most recent call last):
  File "mk_grid.py", line 53, in <module>
    proton_charges.append(int(l[0]))
ValueError: invalid literal for int() with base 10: '6.0'

I think we are on the right track. I will try some other things and come back to you. Thanks for having a look at the code!

**Comment by bast** [comment]
Proton charge needs to be integer. Note to myself to add type hints: https://github.com/dftlibs/numgrid/issues/32

**Comment by heikef** [comment]
@lnw and @bast - now it is running through - it was a type mismatch - I pushed a new version and will continue 

alpha remained a string but has to be a float 

@lnw and @bast Thank you!

**Comment by heikef** [comment]
@bast since you are online what grid would you recommend? 
# generate an atomic grid in the molecular environment
# generate an isolated radial grid
# generate an isolated angular grid

**Comment by bast** [comment]
You want to go for the first one: "atomic grid in the molecular environment".

**Comment by heikef** [comment]
Thank you.

**Comment by lnw** [comment]
and for understanding, those three grids would be 3D, 1D, 2D (on a sphere) respectively?

**Comment by heikef** [comment]
I think 3D. Soon we know. All versions are running through.

**Comment by heikef** [comment]
Do we have to call numgrid.free_atom_grid(context) ?

**Comment by bast** [comment]
> and for understanding, those three grids would be 3D, 1D, 2D (on a sphere) respectively?

yes

**Comment by bast** [comment]
> Do we have to call numgrid.free_atom_grid(context) ?

It is highly recommended to.

**Comment by heikef** [comment]
@lnw the grid has the form of an elipsoid at least when I try to visualize it with gnuplot
@bast should we merge or would it be better to integrate numgrid in another way to gimic? 
As I see it we could read in the new grid and weights and work with it inside the gimic program but this implies more changes plus tests. What do you think?

**Comment by bast** [comment]
The grid should be overlapping concentric spheres around the atom centers.

About the merge: you can send a draft pull request and we can review it there and discuss possible changes.

**Comment by heikef** [comment]
Ok. There will be a lot to discuss. I included the shielding constant calculation plus magnetizability. The values I get based on the fancy numgrid grid are ok. Therefore I think it works. I know that the way it has been programmed is ugly but it is a start and it works.
