### ISSUE TITLE
Describe how to actually run an example

### ISSUE THREAD

**Issue by bast** [qmcurrents/gimic#46]
@heike please describe here: https://github.com/qmcurrents/gimic#example
how to actually run the example that is found here: https://github.com/qmcurrents/gimic/tree/master/examples

We mention that there is an example but we do not show how to run it. Ideally something that can be copy pasted into the terminal.

**Comment by bast** [comment]
Sorry - wrong handle; I meant @heikef.

**Comment by heikef** [comment]
Ok - added to "to do" list

**Comment by heikef** [comment]
I had a look at this. The files are party outdated. There is a severe overlap with the examples we
have in the test directory. I suggest to remove the examples directory and tell the user to look into
the test directory. There one finds also an explanation on how to use it.

**Comment by bast** [comment]
OK if it is outdated, let us remove it. For the general user the test directory is overwhelmingly technical so we will need to create an example where one does not need to read testing script but we can do that later.

**Comment by heikef** [comment]
We can keep the example directory and move one of the test examples there and modify them such that things are user friendly. Ok - I put this on my "to do" list.

**Comment by bast** [comment]
To not spam the other Heike more I will create a new issue and close this one.
