### ISSUE TITLE
update documentation for all available interfaces 

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#49]
We need to add documentation for G09, QChem, Fermion++ and LSDalton.

**Comment by bast** [comment]
I agree - my long term goal is that GIMIC becomes code-independent (as far as this is possible) so that interfaces are maintained by other people in other places. But until then, I agree.

**Comment by heikef** [comment]
I got already some user requests and they promised to help with testing but it would make life easier if we have it for the time being in the documentation. Some interfaces I need to test myself I have to admit to be able to give reasonable user support. However, the people writing the interfaces should also remain involved.

**Comment by bast** [comment]
Yes. Later we should move the interfaces out from this repo. Then we don't have to worry about them. We should only provide one interface where different codes can code against.
