### ISSUE TITLE
Change Sphinx layout for local documentation preview to RTD theme

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#50]
I am not sure if this is the right place to ask this but perhaps it is useful for another user/contributor who wants to help with documentation. 

When I fork and modify the *.rst files and push to my fork I can not "see" the changes that have been introduced. 
I solved it by having my local documentation and running sphinx-build. But the layout is different. However one gets an idea on how the web page looks actually before filing a pull request. 

Is there an easier way to do this? Do I have to set up a new ReadTheDocs link for my fork?

**Comment by bast** [comment]
The central doc only gets updated once the PR is in. Local preview as you do is the right workflow. What we can and possibly should do is to adapt our configuration so that also locally we see the same layout as on RTD.

**Comment by heikef** [comment]
Yes, this would be very reasonable.
