### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by lnw** [qmcurrents/gimic#54]
Compiling gimic on abel is not straightforward, but possible.  The basic problem is, that gimic is really limited to python2, but on abel some python packages only exist as python3 (eg. numpy).

The following works for me:

- load modules:
    - python 3.5
    - cmake
    - intel

- set some aliases:
    - python=python3
    - PYTHON_INCLUDE_DIRS=/cluster/software/.../...3.5m

- setup --fc ifort --cc icc --cxx ccpc mybuild

- cd mybuild; make; make install

- manually change the shebang of all python scripts in mybuild/bin from 3.5 (which was set automatically based on the previous choice) to 2 (which they really are).

It would simplify things a lot, if gimic supported python3.  That refers to cmake as well as the actual scripts.

**Comment by heikef** [comment]
Thanks for pointing this out! We will put it on our "to do" list.

**Comment by lnw** [comment]
What I forgot:

in cmake/FindPython.cmake one needs to add 3.5 (why not also 3.6, 3.4, 3.3, 3.2?) to the known python versions. 

I have hardcoded PYTHON_3_OK to true in cmake/FindPython.cmake (there are more elegant ways)

and I had added 
include_directories($PYTHON_INCLUDE_DIRS $PYTHON_NUMPY_INCLUDE_DIRS)
link_directories($PYTHON_LIBRARY_DIRS)
to CMakeLists.txt

**Comment by heikef** [comment]
Thanks Lukas. Gimic should ideally work platform independent.

**Comment by bast** [comment]
Confirming that it is on our TODO list to simplify compilation considerably during this summer and to enable Python 3 support.

**Comment by lnw** [comment]
Cool!

**Comment by bast** [comment]
Python 3 support is currently hindered by dependency on libgetkw which fails with Python 3. The plan is to replace libgetkw by a more modern implementation.

**Comment by heikef** [comment]
I tried to change getkw.py to python 3 syntax. For the print statements it seems to be ok but I get
other complains. The dictionary "has_key" does not exist in python 3 any more. 
@lnw do you have time to have a look at this?

**Comment by bast** [comment]
We are now writing a "new" getkw which supports Python 3: https://github.com/dev-cafe/parselglossy/
It might be too early, though.

**Comment by heikef** [comment]
Cool! This is a nice initiative! I am sure a lot of people will have use of this. 
Lukas is good in spotting python stuff. It might be that my "messed up" getkw.py could be easily fixed (albeit I doubt it). If yes we would have something that is working, for a while at least, until the fancy stuff from you and Roberto is ready.

**Comment by lnw** [comment]
I guess there is no point in hacking something if Radovan is already working on a proper solution?  Do you currently have a setup where this is more urgent than previously?  Anyway, I can always look at something for the duration of one cup of coffee ...

**Comment by bast** [comment]
I think investing a coffee break time is a good plan. If it takes longer, might be better to wait for me to hook up the new code with GIMIC. Just to not take any false credit - Roberto is the main driving force behind the new project.

**Comment by heikef** [comment]
Look at getkw.py at: https://github.com/heikef/gimic/tree/feature-python3 
It is not working but perhaps you understand where the problem is. I adapted the print statements and removed the "has_key" stuff, which is not supported in python3 any more.

**Comment by lnw** [comment]
Can you be more specific?  What do you do, and in which way does it fail?

**Comment by heikef** [comment]
Just clone the fork and try to run gimic on a small example. Then you will see.

**Comment by lnw** [comment]
I wrote some comments to your patch ... that should fix it.

**Comment by heikef** [comment]
Thank you!

**Comment by heikef** [comment]
I was able to compile and run an example with python 3. Thanks to Lukas for discussion! Now I have another problem. I can not run the testsuite because runtest is not available in python3. What solution would you suggest?

**Comment by heikef** [comment]
Solved it. I had to install pip with conda fist and then simply use pip install runtest. Now the test are running and if they pass I will file a pull request....

**Comment by heikef** [comment]
Works.
