### ISSUE TITLE
Automated testing crashes

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#62]
Automated tests crash. We need to figure out why and fix this.

**Comment by bast** [comment]
The reason is `#include "numpy/arrayobject.h"`, see one of the logs under https://travis-ci.org/qmcurrents/gimic. We had this before. I really need to replace the Cython layer. Working on it. Will try to figure out a workaround until then.

**Comment by heikef** [comment]
Thanks for having a look at this. We should share the new open-shell scripts with the user community as soon as possible. Would it be acceptable to merge even when the tests crash? The reason for the crash is not the new modified script. Or would this be considered as bad practice?

**Comment by bast** [comment]
I believe this is fixed since #64.
