### ISSUE TITLE
And more compilation trouble...

### ISSUE THREAD

**Issue by mariavd** [qmcurrents/gimic#69]
I am trying to compile Gimic on a cluster where Cmake is loaded as a module. I have Anaconda 2, and in my bashrc I have the following set:

```
export PATH=/homeappl/home/mariavd/anaconda2/bin:${PATH}
export PYTHON_LIBRARIES=/homeappl/home/mariavd/anaconda2/lib/libpython2.7.so
export PYTHON_INCLUDE_DIRS=/homeappl/home/mariavd/anaconda2/include/python2.7
```

Yet when I run setup as:
./setup --fc=ifort --extra-fc-flags='-xAVX -axCORE-AVX2,CORE-AVX-I' --cc=icc --extra-cc-flags='-xAVX -axCORE-AVX2,CORE-AVX-I' --cxx=icc --extra-cxx-flags='-xAVX -axCORE-AVX2,CORE-AVX-I' --cmake-options='-DPYTHON_LIBRARIES=/homeappl/home/mariavd/anaconda2/lib/libpython2.7.so -DPYTHON_INCLUDE_DIRS=/homeappl/home/mariavd/anaconda2/include/python2.7'

Cmake still does not know where the Python libraries are....

```
CMake Error at /homeappl/appl_taito/opt/cmake/3.9.0/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
  (Required is at least version "2.7")
Call Stack (most recent call first):
  /homeappl/appl_taito/opt/cmake/3.9.0/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /homeappl/appl_taito/opt/cmake/3.9.0/share/cmake-3.9/Modules/FindPythonLibs.cmake:262 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:23 (find_package)
```

How is that possible?

**Comment by heikef** [comment]
did you use the virtual environment?
http://gimic.readthedocs.io/en/latest/installation.html#installation-on-stallo-supercomputer

**Comment by bast** [comment]
The Python detection is indeed clunky and it is my plan to completely get rid of that CMake code that deals with Python. As a workaround I would indeed try virtual environments. If that fails we can look closer.

**Comment by heikef** [comment]
Can only confirm this. Tested today on the Abel cluster and was not able to install gimic. This is related to issue #54 - The virtual environment did not help either. Gimic seems to be very platform dependent.

**Comment by bast** [comment]
The Python dependency is too entangled. It should not have to detect any Python for the compilation part. That is the goal.

**Comment by mariavd** [comment]
I managed to compile the old version of Gimic which is on the master branch of my fork. It indeed will be nice to have the Python stuff cleaned up because new users might give up trying to compile it.

**Comment by bast** [comment]
The goal is to eventually just do `pip install gimic` and that's it. We will get there.

**Comment by heikef** [comment]
Then we would need to rewrite everything in python. I am not sure if we want this.

**Comment by bast** [comment]
No we would not need to rewrite everything in Python, only the outside layer will be in Python.

**Comment by mariavd** [comment]
I think I finally found the solution to the Python mess. The include directory and the libraries can be specified according to what Python itself reports, instead of exporting them as environment variables (which does not help as I said in my first message). 

This works:

```
$ ./setup --cmake-options="-DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")  -DPYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))")/libpython2.7.so" --prefix=/home/mariavd/gimic/install/
```

But this does not, even though I copied the output from the `python -c` command:
```
$  ./setup --cmake-options="-DPYTHON_INCLUDE_DIRS=/opt/rh/python27/root/usr/include/python2.7 -DPYTHON_LIBRARIES=/opt/rh/python27/root/usr/lib64/libpython2.7.so" --prefix=/home/mariavd/gimic/install/
```

Note that setup complains that it cannot find PYTHON_LIBRARIES and PYTHON_INCLUDE_DIRS, however in order for cmake to work, one needs them in singular, not plural as in the line above. 

Should these options for Cmake be made part of the setup script by default?

**Comment by bast** [comment]
Sorry I don't understand the "singular" vs. "plural". How does the working version differ from the one that is not recognized?

**Comment by mariavd** [comment]
@bast By singular and plural I meant PYTHON_INCLUDE_DIR vs PYTHON_INCLUDE_DIRS and PYTHON_LIBRARY vs PYTHON_LIBRARIES.

So this works:

```
$ ./setup --cmake-options="-DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")  -DPYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))")/libpython2.7.so" --prefix=/home/mariavd/gimic/install/
```

but this does not:

```
$ ./setup --cmake-options="-DPYTHON_INCLUDE_DIRS=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")  -DPYTHON_LIBRARIES=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))")/libpython2.7.so" --prefix=/home/mariavd/gimic/install/
```

And this second line exits with:
```
Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
```

**Comment by bast** [comment]
And singular with explicit paths works?

**Comment by mariavd** [comment]
Yes

**Comment by bast** [comment]
Then the problem is solved? Unless we have somewhere wrong doc suggesting the plural? I would not change the setup script since it seems it does the job?

**Comment by mariavd** [comment]
Running just ./setup with the libraries and include directories exported as environment variables did not work. This is why I did not close the issue.

**Comment by bast** [comment]
Indeed you need to use the `--cmake-options` until we clean up that code. This is also what the documentation suggests: http://gimic.readthedocs.io/en/latest/installation.html#installation-on-stallo-supercomputer

**Comment by mariavd** [comment]
Right, I am closing the issue.
