### ISSUE TITLE
Check of basis set - zero + ordering

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#74]
We should add a check for the coefficients of employed basis sets. It can happen that a coefficient is set to zero and not to another number like 1 for example. Then gimic gives "NaN" as output because there must be somewhere a division by zero, which is not defined. 

Another issue is that some programs do not have a basis set ordering like s, p, d and so on functions but can have suddenly a polarization function in between. This is known for a while but I do not remember if we take care of this and have a check. Probably not but it would be good to have because gimic assumes s, p, d, f and so on functions ordered by increasing l quantum number. 

The check could be done already on the input conversion level, eg. when calling the turbo2gimic.py script or other scripts. The problems described above are know Turbomole issues related to gimic. 

I know this is not urgent but decided to add the issue to avoid that we forget about this. The information might also be considered useful by some other users.

**Comment by bast** [comment]
It's good that you reported this. We will verify this.

**Comment by bast** [comment]
What we need are examples that demonstrate this: a tiny example that demonstrates the NaN, and a tiny example with a different ordering. Then we can build tests around that.

**Comment by heikef** [comment]
Ok - I will set this up.

**Comment by heikef** [comment]
Here comes the "NaN" example. 

Turbomole basis set file:
```
$basis
*
cr def2-TZVP
# cr    (17s11p7d1f) / [6s4p4d1f]     {842111/6311/4111/1}
*
   8  s
  254477.80704      0.23386945693E-03
  38131.797054      0.18142601800E-02
  8675.2930607      0.94363925721E-02
  2455.0099848      0.38343639367E-01
  799.16217787      0.12459194837
  286.90021489      0.29489696029
  111.25413232      0.41846149607
  43.864152636      0.21633763420
   4  s
  279.32669173     -0.23450908111E-01
  86.274732376     -0.11080370027
  13.555756113      0.53028965842
  5.6978112751      0.51603516947
   2  s
  8.5636582615     -0.38109545675
  1.3988296768       1.1991591436
   1  s
 0.57288171116       1.0000000000
   1  s
 0.90096171317E-01   1.0000000000
   1  s
 0.34125885135E-01   1.0000000000
   6  p
  1306.4398864      0.24277326185E-02
  309.25311441      0.19544041017E-01
  98.996273963      0.90651794553E-01
  36.756916451      0.25699279154
  14.566657077      0.40935504891
  5.8739937432      0.23729388849
   3  p
  22.890999695     -0.28166026613E-01
  3.0855001822      0.56034120148
  1.2132329118      0.98119019650
   1  p
 0.44931680699       1.0000000000
   4  d
  43.720074476      0.13622964026E-01
  12.391242652      0.78935180133E-01
  4.2639442006      0.23833840000
  1.5525221790      0.39526851122
   1  d
 0.53761929485      0.41061717056
   1  d
 0.16493173074      0.24440410795
   **1  p                                                                   <--- here is the problem
 0.12067500000       1.0000000000**
   **1  d
 0.51000000000E-01   0.0000000000**
   1  f
  1.1470000000       1.0000000000
*
$end
```
And now the gimic.out file: 

Integrating current density
 *****************************************
 *** Integrating |J| 
 
 ************************************************************
 Induced mod current (au)   :          NaN 
       Positive contribution:     0.000000  (   0.000000 )
       Negative contribution:          NaN  (        NaN )
 
 Induced mod current (nA/T) :          NaN 
       (conversion factor)  :    28.179409
 ************************************************************
 
 *** Integrating current
 
 ************************************************************
    Induced current (au)    :          NaN 
       Positive contribution:     0.000000  (   0.000000 )
       Negative contribution:          NaN  (        NaN )
 
    Induced current (nA/T)  :          NaN 
       (conversion factor)  :    28.179409
 ************************************************************
 
The MOL file:

```
INTGRL        1    0    1    0    0    0    0    0    0   
TURBOMOLE
              Generated by turbo2mol (TM)
2    0            0.10E-08              0    0   
9999.00      3.00
24.0    1 4  6  4  4  1   
CR 1      0.000000000000      0.000000000000     -1.288720858229
     8  1
 254477.8070400000    0.0002338695
  38131.7970540000    0.0018142602
   8675.2930607000    0.0094363926
   2455.0099848000    0.0383436394
    799.1621778700    0.1245919484
    286.9002148900    0.2948969603
    111.2541323200    0.4184614961
     43.8641526360    0.2163376342
      4  1
    279.3266917300   -0.0234509081
     86.2747323760   -0.1108037003
     13.5557561130    0.5302896584
      5.6978112751    0.5160351695
      2  1
      8.5636582615   -0.3810954568
      1.3988296768    1.1991591436
      1  1
      0.5728817112    1.0000000000
      1  1
      0.0900961713    1.0000000000
      1  1
      0.0341258851    1.0000000000
      6  1
   1306.4398864000    0.0024277326
    309.2531144100    0.0195440410
     98.9962739630    0.0906517946
     36.7569164510    0.2569927915
     14.5666570770    0.4093550489
      5.8739937432    0.2372938885
      3  1
     22.8909996950   -0.0281660266
      3.0855001822    0.5603412015
      1.2132329118    0.9811901965
      1  1
      0.4493168070    1.0000000000
      4  1
     43.7200744760    0.0136229640
     12.3912426520    0.0789351801
      4.2639442006    0.2383384000
      1.5525221790    0.3952685112
      1  1
      0.5376192949    0.4106171706
      1  1
      0.1649317307    0.2444041080
      1  1
      0.1206750000    1.0000000000
      1  1
      0.0510000000    0.0000000000
      1  1
      1.1470000000    1.0000000000

```

**Comment by heikef** [comment]
Sorry the system did not accept an upload of all the files. So I copied those parts I consider as relevant.

**Comment by bast** [comment]
Inline is anyway much much better than upload. But please use code blocks to preserve spacing.

**Comment by heikef** [comment]
The example can be separated into two examples by changing:

1 d
0.51000000000E-01 0.0000000000  

to 

1 d
0.51000000000E-01 1.0000000000

**Comment by heikef** [comment]
Ok - did not consider exponents and coefficients as code. -))

**Comment by bast** [comment]
I will rephrase: please make the example copy-pasteable by using code blocks.

**Comment by heikef** [comment]
Please check.

**Comment by bast** [comment]
Nope.

Not a code block:
# This is not copy pasteable
e   x   a   m   p   l   e

This is a code block:
```
# This is copy pasteable
e   x   a   m   p   l   e
```

**Comment by heikef** [comment]
Sorry clicked on "insert code" - did not know that one has to add three`. Now it should work. Please check.
