### ISSUE TITLE
Do we really need to detect PythonLibs?

### ISSUE THREAD

**Issue by bast** [qmcurrents/gimic#76]
Detection is a pain since we need to provide Python header path and library location at configuration time and I am not sure these are even used and therefore possibly not needed? It works for me without.

**Comment by bast** [comment]
Not needed on Stallo either.

**Comment by heikef** [comment]
When it is not needed on a supercomputer then it is also not needed on a laptop. I agree we should remove this. All the python detection stuff is a pain in the neck. Several users already complained about this.
