### ISSUE TITLE
Add more tests to cover functionality

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#94]
We need to add more tests ideally for each input keyword we have. In principle we can stick with the benzene example.

**Comment by mariavd** [comment]
What kind of tests? I can prepare files but what do you mean exactly? Are there any keywords that are missing in the three test input files that we currently have?

**Comment by bast** [comment]
I think this issue is too broad. We need more specific issues, then it is also clear what to do and when the issue is done. Alternatively we should list here what needs to be done for this issue to be resolved.

**Comment by heikef** [comment]
The following keywords could be tested: - all for intgrl - module
grid(bond) = even
spacing
rotation
radius - this one should also be checked with cdens


I will open another issue for more general tests that should be added.
