### ISSUE TITLE
more general tests to be added

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#96]
I think it is important to test the following:

diamag = on/off
paramag = on/off
GIAO = on/off

**Comment by mariavd** [comment]
@heikef Is it really necessary at any point to turn off GIAO? In practice will somebody ever need/want to?

**Comment by bast** [comment]
We want to test both. GIAO gives the better numbers but when assessing the effect, it is nice to have a reference and we want to make sure that the non-GIAO code does not silently break.

**Comment by heikef** [comment]
@mariavd when you add new functionalities it might be necessary to switch GIAO off. Normally you want to use them of course. However, when you look at new developments the first step is always without GIAO's followed by a second step, which introduces GIAO's. I think this test is not urgent but necessary to have. Therefore I filled the issue. I agree with @bast in this point.
